-- ============================================================================
-- Gyaan LMS — Seed data, chunk 2 of 3 (run these AFTER the schema migrations,
-- in order 1 -> 2 -> 3). Split out because the combined file is large enough
-- that some browser-based SQL editors can silently truncate a single paste.
-- ============================================================================

begin;

-- ===========================================================================
-- FLASHCARDS  (27 per module: 9 generic across 3 difficulty tiers + 3 per profession x 6)
-- ===========================================================================

-- ---- chat-basics ----
insert into public.flashcards (deck_id, profession, front, back, order_index, difficulty, card_type) values
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), null,
 'What happens when you send a new message in an existing Claude chat?', 'Claude reads the entire conversation so far — your messages and its replies — before responding, so it can build directly on what came before.', 1, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), null,
 'What is Claude''s "context window"?', 'The amount of conversation Claude can actively read and remember at once — everything within that window shapes its next reply.', 2, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), null,
 'This is the term for starting a brand-new thread with Claude that has no memory of any other chat you''ve had.', 'The term is: **a new conversation** (fresh context).', 3, 'beginner', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), null,
 'Why does it often work better to keep refining one request in the same chat rather than starting over each time?', 'Claude can see your earlier messages and its own prior answers, so follow-ups like "make it shorter" or "use a friendlier tone" land correctly without you having to re-explain the whole task.', 4, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), null,
 'Claude''s first draft of your email is close but too formal — what''s the fastest way to fix it?', 'Reply in the same chat with a specific correction, like "make the tone warmer and more casual" — Claude will revise using the draft it already produced, rather than starting from scratch.', 5, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), null,
 'This is what you should do when a conversation has drifted far from your original goal and keeps producing off-track answers.', 'The term is: **starting a new chat** (rather than fighting an over-long, tangled thread).', 6, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), null,
 'Why can a very long-running chat start producing worse answers even though nothing about your questions changed?', 'As a conversation grows, older turns can fall outside the context window, or the thread accumulates conflicting instructions and dead-end tangents — both dilute what Claude can usefully draw on. A shorter, focused thread — or a fresh one with a clean summary — often performs better.', 7, 'advanced', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), null,
 'You''ve been iterating on a strategy doc for an hour in one chat. Claude now contradicts something it said 30 messages ago and seems to have lost your key constraints.', 'This is a sign the thread has grown past what''s useful — summarize the decisions and constraints that still matter, start a new chat, and paste that summary in as the opening message so Claude starts from a clean, accurate footing.', 8, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), null,
 'This describes the trade-off between continuing one long chat (rich shared context, but potential drift and dilution) versus starting fresh (clean slate, but you must manually re-supply context).', 'The term is: **conversation length trade-off** (context depth vs. context cleanliness).', 9, 'advanced', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'recruitment',
 'As a recruiter, what''s a simple first use of a Claude chat?', 'Ask Claude to draft a first-pass outreach message to a candidate, then refine it in the same thread until the tone and details feel right.', 10, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'recruitment',
 'You asked Claude to write a job description and it''s good but missing your company''s benefits section — what''s next?', 'Don''t start over — reply in the same chat with the missing details ("add a benefits section covering health, PTO, and remote flexibility") and Claude will fold it into the existing draft.', 11, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'recruitment',
 'You''re screening notes across 15 candidates in one long chat and Claude starts mixing up which notes belong to which candidate.', 'The thread has gotten too long and cluttered for Claude to track cleanly — split the work into one chat per candidate, or per batch, so each conversation''s context stays focused and accurate.', 12, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'marketing',
 'If Claude''s first draft of a social post isn''t quite your brand''s voice, what should you do?', 'Reply in the same chat and describe the voice you want ("more playful, shorter sentences") — Claude adjusts the existing draft instead of you rewriting it yourself.', 13, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'marketing',
 'This is the practice of sending a series of follow-up corrections in one chat — "punchier headline," "cut the jargon," "add a CTA" — instead of describing everything perfectly up front.', 'The term is: **iterating** (refining through conversation rather than a single perfect prompt).', 14, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'marketing',
 'You''ve been iterating on a campaign brief for 50+ messages and Claude just suggested an idea you already rejected earlier in the thread.', 'The chat has likely grown long enough that earlier turns are getting crowded out. Summarize the current direction and firm rejections in a short recap, and continue in a new chat so those decisions stay visible.', 15, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'sales',
 'What''s a good first message to send Claude when prepping for a sales call?', 'Give it the basics — who the prospect is, what they do, and what you want out of the call — so Claude has real context for the outline or talking points it drafts.', 16, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'sales',
 'Why should you keep asking follow-up questions in the same chat instead of re-describing your deal from scratch each time?', 'Claude already has the account context, objections, and prior drafts in that thread — follow-ups like "now write the follow-up email" reuse that context automatically, saving you retyping and keeping details consistent.', 17, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'sales',
 'This is what you should do before starting a new chat about a deal you''ve discussed at length before, so Claude isn''t starting cold.', 'The term is: **carrying context forward** (pasting a short recap of the deal stage, key objections, and next step into the new chat''s opening message).', 18, 'advanced', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'engineering',
 'You pasted an error message to Claude and got a fix — what should you do if it doesn''t work?', 'Reply in the same chat with what happened when you tried it — Claude will see the original error and its own suggestion, and can adjust rather than guess again from zero.', 19, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'engineering',
 'You''re debugging in one chat, and now want to ask about an unrelated formatting question for a different file.', 'Consider starting a second chat for the unrelated question — keeping topics separate avoids muddying the debugging thread''s context with unrelated details.', 20, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'engineering',
 'A long pair-programming chat has Claude proposing a fix that ignores a constraint you mentioned 60 messages ago.', 'That constraint has likely aged out of what''s easy for Claude to weigh — restate key constraints periodically in long technical threads, or start a fresh chat with a short spec summarizing them.', 21, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'hr',
 'What''s a low-risk first task for a new Claude chat if you work in HR?', 'Ask it to draft something routine, like a PTO policy FAQ answer or an onboarding checklist, then read it over and refine the wording together in the same chat.', 22, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'hr',
 'This is what''s happening when you tell Claude "keep everything the same but make section 2 more concise" and it edits only that part.', 'The term is: **targeted iteration** (giving a precise follow-up instruction so Claude revises just the part that needs it).', 23, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'hr',
 'You''re drafting a sensitive policy update across a long chat, and Claude''s latest version quietly drops a caveat you added earlier.', 'In long threads, earlier specific instructions can get crowded out. Re-state the caveat explicitly in your next message, and for anything sensitive, do a final full read-through rather than trusting incremental edits alone.', 24, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'finance',
 'You asked Claude to summarize a budget memo and want a shorter version — what do you do?', 'Just ask in the same chat — "make that three bullet points" — Claude will condense the summary it already gave you rather than needing the memo again.', 25, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'finance',
 'Why is it worth telling Claude your audience (e.g., "this is for the board" vs. "for my team") early in a chat?', 'That framing carries through the rest of the conversation — every later draft and follow-up will lean on it, so you don''t need to repeat the audience each time you ask for a revision.', 26, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='chat-basics')), 'finance',
 'You''ve built up a detailed forecast discussion over many messages, and now need to share the key assumptions with a colleague who wasn''t in the chat.', 'Ask Claude, in that same thread, to summarize the finalized assumptions and decisions into a clean standalone recap — that turns a long working conversation into something shareable without you re-deriving it.', 27, 'advanced', 'scenario');

-- ---- prompting ----
insert into public.flashcards (deck_id, profession, front, back, order_index, difficulty, card_type) values
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), null,
 'What makes a prompt "specific" rather than vague?', 'It states exactly what you want — the format, length, audience, and any constraints — instead of leaving Claude to guess your intent.', 1, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), null,
 'What is a "role" prompt?', 'Asking Claude to respond as if it were a particular persona or expert (e.g., "as a patent attorney") so its tone, vocabulary, and focus match that perspective.', 2, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), null,
 'This is the term for giving Claude one or more worked examples of the exact output you want, so it can match that pattern.', 'The term is: **few-shot prompting**.', 3, 'beginner', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), null,
 'Why does adding context (audience, purpose, constraints) usually improve Claude''s first draft more than adding extra adjectives does?', 'Context narrows down what a "good" answer actually looks like for your situation, while adjectives like "great" or "professional" are subjective and don''t tell Claude what to prioritize.', 4, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), null,
 'You ask Claude to "write a summary" and get something too long and generic — what''s missing from the prompt?', 'Specificity — state the target length, the audience, and what should be emphasized, so Claude knows what "good" means for this particular summary.', 5, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), null,
 'This is the practice of telling Claude not just what to produce, but the exact structure or format it should follow.', 'The term is: **format instructions** (specifying output structure like bullet points, a table, or a fixed number of sections).', 6, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), null,
 'When should you use few-shot examples instead of just describing what you want in words?', 'When the output has a specific style, structure, or nuance that''s hard to fully capture in a description — showing 1-3 examples of the exact pattern often communicates it faster and more reliably than explaining it.', 7, 'advanced', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), null,
 'You''ve given Claude a detailed role, clear format instructions, and one example — but the output still misses the mark on tone.', 'Check whether your example itself actually demonstrates the tone you want — a mismatched or overly formal example can override written instructions, since Claude tends to weight concrete examples heavily.', 8, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), null,
 'This describes combining a role, relevant context, and one or more examples in a single prompt, rather than relying on any one technique alone.', 'The term is: **layered prompting** (stacking specificity, role, and examples together for a more reliable result).', 9, 'advanced', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'recruitment',
 'What''s one simple way to make a job-description prompt more specific?', 'Name the exact role, seniority level, must-have skills, and where it will be posted — instead of just saying "write a job description for a developer."', 10, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'recruitment',
 'You ask Claude to "write outreach messages" for five different candidates and get near-identical generic notes.', 'Give Claude each candidate''s specific background and what drew you to their profile — specificity is what turns a form-letter feel into a message that reads as personalized.', 11, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'recruitment',
 'You want Claude to match your team''s exact interview-scorecard style, but describing the format in words keeps coming out slightly wrong.', 'Paste one completed scorecard as a few-shot example — showing the exact structure and level of detail communicates the format far more reliably than a written description.', 12, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'marketing',
 'What does it mean to give Claude a "role" when drafting marketing copy?', 'Asking it to write as a specific persona — e.g., "as a witty social media manager for a sneaker brand" — so the voice and priorities match that role.', 13, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'marketing',
 'This is what you''re doing when you paste three of your brand''s best-performing headlines before asking Claude to write new ones.', 'The term is: **few-shot prompting** (showing examples of the pattern you want repeated).', 14, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'marketing',
 'Claude''s ad copy is on-brand in tone but keeps missing your target audience''s actual pain points.', 'Tone alone isn''t enough context — add specifics about who the audience is and what problem they''re trying to solve, since audience context shapes content in a way persona alone can''t.', 15, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'sales',
 'Why is "write a follow-up email to a prospect" a weak prompt on its own?', 'It''s missing context — who the prospect is, what was discussed, and what action you want next — so Claude has to guess at the details that actually matter.', 16, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'sales',
 'How does telling Claude "respond as a sales coach reviewing this pitch" change its output?', 'It''s a role prompt — Claude shifts its focus toward critique, structure, and persuasiveness, the way an actual sales coach would, rather than just rewriting the pitch politely.', 17, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'sales',
 'You want objection-handling responses that match your team''s specific style — direct, but never pushy.', 'Give Claude two or three real examples of your team''s best objection responses as few-shot examples — that concrete pattern teaches the "direct but not pushy" balance more reliably than describing it abstractly.', 18, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'engineering',
 'What''s a simple way to make a code-request prompt more specific?', 'Name the language, the function''s exact inputs and outputs, and any constraints (e.g., no external libraries) rather than just describing the general goal.', 19, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'engineering',
 'You ask Claude to "review this code" and get generic praise with no real feedback.', 'Give it a role and focus — "as a senior reviewer, focus only on performance and edge cases" — narrowing the task produces sharper, more useful feedback than an open-ended request.', 20, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'engineering',
 'This is what you''re doing when you show Claude one function you''ve already written in your team''s exact style before asking it to write a second, similar one.', 'The term is: **few-shot prompting** (letting a concrete example carry style conventions words alone often miss).', 21, 'advanced', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'hr',
 'What makes "write a policy" a vague prompt?', 'It doesn''t say which policy, for what situation, or in what tone — Claude has to guess the context that actually determines what a good answer looks like.', 22, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'hr',
 'Why might asking Claude to "respond as an employee relations specialist" improve a tricky policy answer?', 'A role prompt shifts Claude''s focus toward the considerations that specialist would prioritize — fairness, tone, and compliance — rather than a generic informational answer.', 23, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'hr',
 'You need Claude to write several policy FAQ answers in your company''s exact voice, but a written description of that voice keeps falling short.', 'Paste two or three existing FAQ answers as examples — few-shot examples transmit voice and structure more precisely than adjectives like "friendly but professional" ever can.', 24, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'finance',
 'What''s missing from the prompt "summarize this report"?', 'Specificity — the audience, desired length, and what to emphasize (e.g., risks vs. opportunities) all shape what a useful summary looks like.', 25, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'finance',
 'This is what''s happening when you tell Claude "explain this like you''re briefing a first-time investor with no finance background."', 'The term is: **role prompting** (framing the audience/persona so Claude adjusts vocabulary and depth accordingly).', 26, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='prompting')), 'finance',
 'You want Claude to produce variance-analysis commentary that matches the exact structure your finance team always uses.', 'Provide one completed example of the commentary format as a few-shot example — that concrete structure is far more reliable than describing "our usual format" in words.', 27, 'advanced', 'scenario');

-- ---- projects ----
insert into public.flashcards (deck_id, profession, front, back, order_index, difficulty, card_type) values
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), null,
 'What is a Claude "Project"?', 'A dedicated space that holds custom instructions and reference knowledge shared across every chat inside it, so you don''t have to re-explain context each time.', 1, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), null,
 'What are "custom instructions" in a Project?', 'Standing guidance you set once — like tone, format preferences, or house style — that Claude automatically applies to every conversation in that Project.', 2, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), null,
 'This is the term for files or notes you add to a Project so Claude can reference them in every chat within it.', 'The term is: **project knowledge**.', 3, 'beginner', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), null,
 'Why do Projects save time compared to individual chats for recurring work?', 'Instead of re-explaining your context, style, or reference material in every new chat, you set it up once in the Project and every conversation inside it automatically has access.', 4, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), null,
 'You do the same type of weekly report every week, retyping the same background each time in a fresh chat.', 'Set up a Project with that background and formatting preferences as custom instructions and project knowledge — then each week you just start a new chat inside it and ask for the report.', 5, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), null,
 'This is what happens when you update a Project''s knowledge files — every future chat in that Project automatically benefits, without you touching old chats.', 'The term is: **shared/persistent project context**.', 6, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), null,
 'What''s the trade-off to watch for when you add a lot of reference material to a Project''s knowledge?', 'More material gives Claude more to draw on, but overly long or outdated project knowledge can crowd out what''s actually relevant to a given chat — keep it curated and current, not just comprehensive.', 7, 'advanced', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), null,
 'A Project''s custom instructions say to always use a formal tone, but for one specific chat you need something more casual.', 'You can override standing instructions within a single chat by explicitly saying so — an in-chat request generally takes precedence over the Project''s default guidance for that conversation.', 8, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), null,
 'This describes the risk of letting a Project''s knowledge base grow indefinitely without pruning outdated files.', 'The term is: **knowledge staleness** (old or conflicting reference material degrading the quality of answers).', 9, 'advanced', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'recruitment',
 'What might a recruiter add as project knowledge in a "Candidate Communications" Project?', 'Templates for outreach, past job descriptions, and the company''s tone-of-voice guide — so Claude can draw on them without you re-pasting each time.', 10, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'recruitment',
 'You keep re-explaining your company''s interview process to Claude in every new chat about candidate prep.', 'Move that explanation into a Project''s custom instructions once — every future chat in that Project will already know the process.', 11, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'recruitment',
 'Your "Hiring" Project''s knowledge includes an old job-leveling guide that was replaced last quarter.', 'Remove or update the outdated file — stale project knowledge can lead Claude to apply criteria that no longer reflect current hiring standards.', 12, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'marketing',
 'What''s a natural use of a Project for a marketing team?', 'A "Brand Voice" Project holding style guides, past campaigns, and messaging pillars, so every content request in that Project stays on-brand automatically.', 13, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'marketing',
 'This is what''s happening when a marketer uploads their brand guidelines once into a Project, instead of pasting them into every single content chat.', 'The term is: **project knowledge** (persistent reference material shared across the Project''s chats).', 14, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'marketing',
 'A "Campaigns" Project''s custom instructions default to a bold, energetic voice, but this week''s brief calls for a somber, empathetic tone.', 'State the override explicitly in that chat — an in-conversation instruction takes precedence over the Project''s standing tone default for that one chat.', 15, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'sales',
 'What could a sales rep store in a "Deal Prep" Project?', 'Product one-pagers, competitor comparisons, and objection-handling notes — so every deal-related chat can reference them automatically.', 16, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'sales',
 'Why is a Project better than one long ongoing chat for tracking multiple accounts?', 'A Project lets you start a clean chat per account while still sharing common reference material (like product info) across all of them — you get fresh context per deal without losing shared knowledge.', 17, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'sales',
 'Your "Enterprise Deals" Project knowledge still lists pricing from two quarters ago.', 'Update the pricing file — outdated project knowledge can quietly produce proposals or talking points based on numbers that are no longer accurate.', 18, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'engineering',
 'What might an engineer add to a Project''s knowledge for a specific codebase?', 'Architecture notes, coding conventions, or key API references — so Claude has that context in every chat about that codebase.', 19, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'engineering',
 'You keep pasting the same style guide into every new chat about your team''s codebase.', 'Add it once as project knowledge in a dedicated Project — every future chat inside it will already have that context available.', 20, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'engineering',
 'Your team''s Project knowledge still includes a deprecated API''s documentation alongside the current one.', 'Remove the deprecated docs — leaving both can cause Claude to mix guidance from the old and new APIs, producing subtly broken suggestions.', 21, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'hr',
 'What''s a good use of a Project for HR?', 'An "Employee Policies" Project holding the current handbook and FAQ answers, so policy questions get answered consistently across chats.', 22, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'hr',
 'This is what lets every chat inside an HR Project consistently reference the same up-to-date handbook, without re-uploading it each time.', 'The term is: **project knowledge** (shared reference files available to every chat in the Project).', 23, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'hr',
 'An "Onboarding" Project''s custom instructions specify a warm, welcoming tone by default, but you''re drafting a formal compliance notice this week.', 'Explicitly state the tone you need for that chat — an in-chat instruction overrides the Project''s default tone just for that conversation.', 24, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'finance',
 'What could a finance team store as project knowledge in a "Monthly Close" Project?', 'The chart of accounts, prior month templates, and reporting standards — so recurring close tasks don''t require re-explaining the setup each time.', 25, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'finance',
 'Why does using a Project help with consistency across multiple analysts on the same team?', 'Everyone''s chats inside the Project draw on the same custom instructions and knowledge files, so outputs stay aligned with shared standards instead of drifting based on who''s asking.', 26, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='projects')), 'finance',
 'Your "Forecasting" Project''s knowledge base has grown to include several superseded versions of the assumptions file.', 'Prune the outdated versions — a cluttered, conflicting knowledge base makes it harder for Claude to reliably pick the current, correct assumptions.', 27, 'advanced', 'scenario');

-- ---- artifacts ----
insert into public.flashcards (deck_id, profession, front, back, order_index, difficulty, card_type) values
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), null,
 'What is an Artifact in Claude?', 'A separate editable pane where Claude puts substantial content it creates — like a document, code, or a visual — so you can view, edit, and iterate on it apart from the chat itself.', 1, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), null,
 'What kinds of things can appear as Artifacts?', 'Documents, code snippets, websites, diagrams, and interactive apps — basically any sizeable, self-contained piece of content worth viewing and editing on its own.', 2, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), null,
 'This is the term for asking Claude to revise something already showing in the side panel, rather than rewriting it from scratch in the chat.', 'The term is: **iterating on an Artifact**.', 3, 'beginner', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), null,
 'Why are Artifacts useful for content you plan to keep revising?', 'They live in a separate, persistent view you can keep referring back to and editing directly, instead of scrolling through chat messages to find the latest version buried in the conversation.', 4, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), null,
 'You asked Claude to build a simple interactive calculator and it appeared in a side panel you can click and test.', 'That''s an Artifact — because it''s a real, self-contained interactive piece of content, Claude renders it separately so you can actually use it, not just read about it.', 5, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), null,
 'This is what you''re doing when you tell Claude "change the header color to blue" about the app currently shown in the side panel.', 'The term is: **iterating on an Artifact** (a targeted edit to existing generated content).', 6, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), null,
 'Why might you deliberately ask Claude to make something an Artifact rather than just describe it in chat?', 'When the deliverable is meant to be reused, shared, viewed as a finished thing, or interacted with (like a working app or a polished document), an Artifact gives you a clean, standalone version — separate from the back-and-forth conversation that produced it.', 7, 'advanced', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), null,
 'You''ve been iterating on a dashboard Artifact for many rounds, and now want a totally different visual style rather than a tweak.', 'For a major change, it''s often cleaner to describe the new direction clearly and let Claude regenerate significant portions, rather than nudging incrementally — small iterative edits are best for refinements, not overhauls.', 8, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), null,
 'This describes the judgment call between making a small targeted edit request versus asking for a substantial regeneration of an Artifact.', 'The term is: **iteration scope** (deciding whether a change warrants a tweak or a rebuild).', 9, 'advanced', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'recruitment',
 'What''s a good use of an Artifact for a recruiter?', 'A polished candidate scorecard template or a formatted job posting — content substantial and reusable enough to be worth its own editable view.', 10, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'recruitment',
 'You want to tweak the layout of a candidate comparison table Claude generated as an Artifact.', 'Ask Claude directly to adjust that Artifact — e.g., "add a column for years of experience" — and it will update the existing table rather than starting a new one.', 11, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'recruitment',
 'You''ve iterated many small tweaks into a hiring dashboard Artifact, and now want to switch it from a table layout to a visual card layout entirely.', 'That''s a big enough shift to ask for a rebuild — describe the new card-based design clearly and let Claude regenerate the Artifact, rather than nudging the table incrementally toward something it was never built to be.', 12, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'marketing',
 'What kind of marketing content is a good fit for an Artifact?', 'A landing page mockup, a formatted content calendar, or a one-page campaign brief — substantial content worth viewing and editing on its own.', 13, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'marketing',
 'This is what''s happening when you ask Claude to "make the CTA button bigger" on the landing page currently shown in the side panel.', 'The term is: **iterating on an Artifact**.', 14, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'marketing',
 'A campaign one-pager Artifact has gone through a dozen small edits and no longer matches the clean structure you originally wanted.', 'Rather than one more small nudge, describe the structure you actually want now and ask Claude to regenerate the one-pager — many small edits can compound into something messier than a clean rebuild.', 15, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'sales',
 'What''s a natural Artifact for a sales rep to request?', 'A formatted proposal document or a pricing comparison table — content meant to be reviewed, edited, and eventually shared as a finished piece.', 16, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'sales',
 'You''re refining a proposal Artifact and need one section reworded without touching the rest.', 'Ask specifically for that section — "reword the executive summary, keep everything else" — Claude edits just that part of the existing Artifact.', 17, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'sales',
 'Your proposal Artifact has been tweaked so many times through small requests that its structure has become inconsistent.', 'Describe the ideal structure clearly and ask for a fresh version — a full regeneration often produces a cleaner result than continuing to patch an Artifact that''s drifted through many incremental edits.', 18, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'engineering',
 'Why would Claude put a piece of code in an Artifact instead of just showing it in chat?', 'Substantial or runnable code is typically rendered as an Artifact so you can view, edit, and (for supported types) interact with it directly, separate from the conversation.', 19, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'engineering',
 'Claude built a small interactive tool as an Artifact and you want to add one more input field.', 'Ask for that specific change in the chat — "add a field for the discount percentage" — and Claude updates the existing Artifact''s code rather than rebuilding everything from scratch.', 20, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'engineering',
 'An Artifact-based prototype has grown through many incremental feature requests and its structure is getting tangled.', 'That''s a sign it''s time for a larger regeneration rather than another patch — describe the cleaned-up structure you want and let Claude rebuild it, since incremental patches on a tangled base tend to compound the mess.', 21, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'hr',
 'What HR content is a good fit for an Artifact?', 'A formatted onboarding checklist or a polished policy handout — content substantial enough to be worth its own editable, reusable view.', 22, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'hr',
 'This is what''s happening when you ask Claude to "shorten the PTO section" on the handbook currently open in the side panel.', 'The term is: **iterating on an Artifact**.', 23, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'hr',
 'An onboarding checklist Artifact has been edited piecemeal so many times that sections now overlap and repeat.', 'Ask Claude to regenerate the checklist from a clear, current outline rather than trimming it again — a rebuild avoids carrying forward the redundancy that small edits accumulated.', 24, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'finance',
 'What''s a good use of an Artifact for finance work?', 'A formatted budget summary or a variance-analysis table — substantial, structured content worth its own editable view outside the chat.', 25, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'finance',
 'You want to update just the Q3 numbers in a forecast table Artifact, leaving everything else untouched.', 'Ask specifically for that update — "update only the Q3 column with these figures" — Claude edits just that part of the existing table.', 26, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='artifacts')), 'finance',
 'A budget Artifact has accumulated many small structural tweaks over weeks and no longer matches your reporting standard cleanly.', 'Rather than another incremental fix, describe the standard structure you need and ask Claude to regenerate the table — a clean rebuild avoids compounding small inconsistencies from prior edits.', 27, 'advanced', 'scenario');

-- ---- tool-use ----
insert into public.flashcards (deck_id, profession, front, back, order_index, difficulty, card_type) values
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), null,
 'What does it mean for Claude to "use a tool"?', 'Claude can call on external capabilities beyond its own knowledge — like searching the web or pulling data from a connected app — to help answer your request, then use those results in its reply.', 1, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), null,
 'What is web search used for in a Claude conversation?', 'It lets Claude look up current information beyond its training data — useful for recent events, live data, or anything that might have changed since it was trained.', 2, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), null,
 'This is the term for a pre-built integration that lets Claude read from or act on a specific external app, like a calendar or a docs tool.', 'The term is: **connector**.', 3, 'beginner', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), null,
 'Why might Claude decide to search the web instead of just answering from what it already knows?', 'If a question depends on current, time-sensitive, or very specific information — like today''s stock price or a recent product release — Claude''s training data alone may be outdated or incomplete, so a live search fills that gap.', 4, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), null,
 'You ask Claude about a competitor''s product update that launched this week.', 'This is a good case for web search — Claude''s training data has a cutoff, so recent events need a live lookup to be accurate.', 5, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), null,
 'This is the open standard that lets Claude connect to external tools and data sources in a consistent, extensible way.', 'The term is: **MCP (Model Context Protocol)**.', 6, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), null,
 'Why is it worth checking the source Claude cites after a web search, rather than trusting the summary alone?', 'Search results can vary in reliability, be outdated despite being "live," or be summarized imprecisely — for anything decision-critical, verifying the underlying source protects you from acting on a subtly wrong synthesis.', 7, 'advanced', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), null,
 'You''ve connected Claude to your team''s project-management tool, and it now pulls in task data automatically for status updates.', 'Because a connector gives Claude read (and sometimes write) access to real data, review what it''s pulling in and what actions it''s taking carefully — an incorrect assumption acted on through a connector affects real systems, not just a chat reply.', 8, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), null,
 'This describes the general judgment needed when giving Claude tool or connector access: weighing the convenience of automated actions against the risk of it acting on incomplete or misread information.', 'The term is: **tool-use oversight** (staying in the loop on what tools are doing on your behalf).', 9, 'advanced', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'recruitment',
 'How might web search help a recruiter using Claude?', 'It can look up current salary benchmarks or recent company news about a candidate''s background — information beyond what Claude already knows from training.', 10, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'recruitment',
 'You want Claude to check a candidate''s public professional presence as part of prep for an interview.', 'Web search can pull recent, current information for this kind of lookup, since a candidate''s public profile can change frequently and Claude''s training data may be out of date.', 11, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'recruitment',
 'A calendar connector now lets Claude auto-schedule interviews based on availability it reads directly.', 'Because this connector can take real scheduling actions, double-check the first several bookings it makes closely — a misread availability slot creates a real calendar conflict, not just a wrong chat answer.', 12, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'marketing',
 'Why might a marketer use web search inside a Claude chat?', 'To pull in current trends, competitor campaigns, or recent news relevant to a piece of content — things beyond Claude''s training cutoff.', 13, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'marketing',
 'This is the term for connecting Claude to your team''s analytics or content-management tool so it can read real campaign data directly.', 'The term is: **connector**.', 14, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'marketing',
 'Claude searched the web for a competitor''s latest pricing and summarized it, but the number seems oddly specific.', 'Check the original source before using that number in a strategy document — a summarized search result can occasionally be imprecise, and decision-critical numbers deserve direct verification.', 15, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'sales',
 'How could web search help a sales rep prep for a call?', 'It can pull recent news about the prospect''s company — funding rounds, leadership changes, or product launches — that Claude wouldn''t know from training alone.', 16, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'sales',
 'You want Claude to pull the latest deal stage and notes directly from your CRM before drafting a follow-up.', 'This is a good use for a connector — linking Claude to your CRM lets it read real, current deal data instead of you manually copying it in.', 17, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'sales',
 'A CRM connector now lets Claude update deal stages automatically based on your conversation notes.', 'Because this connector writes real data back into your CRM, review its updates before trusting them fully — an inaccurate note-to-stage mapping quietly corrupts your actual pipeline, not just a chat summary.', 18, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'engineering',
 'Why might an engineer use web search inside a Claude chat?', 'To look up current documentation for a library, a recent CVE, or a framework update released after Claude''s training cutoff.', 19, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'engineering',
 'This is the open standard that lets Claude connect consistently to developer tools like a codebase, issue tracker, or internal API.', 'The term is: **MCP (Model Context Protocol)**.', 20, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'engineering',
 'You''ve connected Claude to your team''s issue tracker via MCP, and it now proposes closing tickets based on its read of recent commits.', 'Review its proposed actions before it closes anything — a connector acting on a misread commit history can close a real ticket incorrectly, which is a different kind of mistake than just a wrong chat answer.', 21, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'hr',
 'How might web search help someone working in HR?', 'It can look up current employment law changes or benchmark benefits data — information that shifts over time and may be newer than Claude''s training data.', 22, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'hr',
 'Why would connecting Claude to your HRIS (HR information system) via a connector be useful?', 'It lets Claude read real, current employee data directly — like headcount or leave balances — instead of you manually exporting and pasting reports each time.', 23, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'hr',
 'An HRIS connector now lets Claude draft communications referencing specific employees'' leave balances it reads directly.', 'Because this touches sensitive personal data pulled automatically, review what''s being read and shared carefully — an incorrect or overly broad data pull through a connector is a real privacy risk, not just a wrong answer.', 24, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'finance',
 'How might web search help someone doing finance work with Claude?', 'It can look up a current exchange rate or a recent market move — live data that changes constantly and wouldn''t be current in Claude''s training.', 25, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'finance',
 'You want Claude to pull the latest numbers directly from your accounting software instead of you exporting a report each time.', 'This is a good use for a connector — it lets Claude read current data directly from the source instead of relying on a manually pasted, possibly stale export.', 26, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='tool-use')), 'finance',
 'A connector now lets Claude pull live figures from your accounting system directly into a forecast draft.', 'Because forecasts inform real decisions, spot-check the pulled figures against the source before trusting the draft fully — a connector reading the wrong period or account can silently skew numbers that look correct at a glance.', 27, 'advanced', 'scenario');

-- ---- workflows ----
insert into public.flashcards (deck_id, profession, front, back, order_index, difficulty, card_type) values
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), null,
 'What is a "workflow" when working with Claude?', 'A sequence of connected steps — often several prompts in a row — that together accomplish a larger task, rather than relying on a single one-shot request.', 1, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), null,
 'Why break a big task into multiple smaller steps for Claude instead of one giant prompt?', 'Smaller steps are easier to check and correct along the way — you can catch a problem early rather than discovering it buried inside one huge, complex output.', 2, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), null,
 'This is the term for a workflow you''ve refined once and can reuse for the same type of task going forward.', 'The term is: **a repeatable prompt chain**.', 3, 'beginner', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), null,
 'What''s the benefit of reviewing Claude''s output at each step of a multi-step workflow, rather than only at the very end?', 'Catching an issue early means it doesn''t compound into every step that builds on it — a mistake at step one silently affects steps two through five if it goes unnoticed until the final result.', 4, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), null,
 'You need Claude to research a topic, draft an outline, then write a full report — all connected pieces of one bigger task.', 'Treat this as a workflow — do the research step first, confirm it looks right, then explicitly ask for the outline based on that research, then the draft — checking in between each step rather than asking for everything at once.', 5, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), null,
 'This is what you''re doing when you save the sequence of prompts that worked well for a recurring task, so you can reuse it next time with new details swapped in.', 'The term is: **building a repeatable workflow**.', 6, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), null,
 'How should you decide where to draw the boundaries between steps in a multi-step workflow?', 'Split at points where you''d actually want to review or could plausibly want to redirect the work — if a step''s output feeds directly and reliably into the next with no real decision point, it''s often fine to combine them — splitting everywhere adds friction without adding safety.', 7, 'advanced', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), null,
 'A workflow you built for one recurring report works well, but a slightly different report needs a modified version of two of the five steps.', 'Rather than building an entirely new workflow, adapt the existing one — reuse the three steps that transfer directly and only rework the two that need to change, since most of the sequence''s value carries over.', 8, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), null,
 'This describes combining several Claude capabilities in sequence — like research via web search, then drafting, then a formatted Artifact — into one coherent multi-step process.', 'The term is: **an end-to-end workflow**.', 9, 'advanced', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'recruitment',
 'What might a recruitment workflow with Claude look like end-to-end?', 'Draft the job posting, then generate outreach messages, then create interview questions — three connected steps that build a complete hiring kit rather than one big request.', 10, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'recruitment',
 'You need to screen resumes, then draft personalized outreach for the strong ones, then prep interview questions for whoever responds.', 'Run this as a workflow — screen first and review the shortlist, then draft outreach for just that shortlist, then prep questions only once interviews are actually scheduled, checking in between each stage.', 11, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'recruitment',
 'Your resume-screening-to-outreach workflow works well, but a new role needs different screening criteria and a different outreach tone.', 'Reuse the overall structure but swap in the new criteria at the screening step and the new tone at the outreach step — the workflow''s shape still holds even though two of its steps need real changes.', 12, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'marketing',
 'What could a content-creation workflow with Claude include end-to-end?', 'Research the topic, draft an outline, write the full post, then adapt it into social captions — a chain of connected steps rather than one giant prompt.', 13, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'marketing',
 'Why check the outline before asking Claude to write the full blog post from it?', 'If the outline''s structure or angle is off, catching it early saves you from a full draft built on the wrong foundation — reviewing at each step avoids the mistake compounding.', 14, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'marketing',
 'Your blog-post workflow (research, outline, draft, social recap) works well, but this campaign needs a video script instead of a blog post at the drafting step.', 'Keep the research and outline steps as-is, and swap only the drafting step''s output format — most of the workflow''s value is in the earlier steps, which don''t need to change just because the final format does.', 15, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'sales',
 'What could a deal-prep workflow with Claude look like end-to-end?', 'Research the prospect, draft talking points, then prepare a follow-up email template — connected steps building toward a full call-ready package.', 16, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'sales',
 'You want Claude to research a prospect, then draft a personalized pitch, then create objection-handling notes — one after another.', 'Treat it as a workflow — confirm the research looks accurate first, since the pitch and objection notes both build on it, and an error there would carry through the rest.', 17, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'sales',
 'Your outreach workflow (research, pitch draft, follow-up email) works for cold prospects, but warm referrals need a different opening in the pitch step.', 'Keep the research and follow-up steps unchanged, and only adjust the pitch step''s opening for referral context — most of the sequence transfers directly.', 18, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'engineering',
 'What could a code-review workflow with Claude include end-to-end?', 'Summarize the diff, flag potential issues, then draft review comments — a chain of steps rather than one request to "review this."', 19, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'engineering',
 'This is what you''re doing when you check that Claude''s bug diagnosis is correct before asking it to draft the actual fix.', 'The term is: **reviewing at each step** (catching an issue before it compounds into the next step).', 20, 'intermediate', 'reverse'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'engineering',
 'Your bug-triage workflow (reproduce, diagnose, draft fix) works well for backend bugs, but frontend bugs need a different reproduction step.', 'Reuse the diagnose and draft-fix steps as-is, and only rework the reproduction step for frontend specifics — the overall shape of the workflow still holds.', 21, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'hr',
 'What could an onboarding-content workflow with Claude look like end-to-end?', 'Draft the welcome email, then the first-week checklist, then FAQ answers — a sequence of connected pieces rather than one massive request.', 22, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'hr',
 'Why review the welcome email''s tone before asking Claude to extend that same tone across the whole onboarding checklist?', 'If the tone is off in the first piece, catching it there prevents that same issue from repeating across every subsequent document in the sequence.', 23, 'intermediate', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'hr',
 'Your onboarding workflow (welcome email, checklist, FAQ) works well, but a new remote-hire track needs a different checklist step.', 'Keep the welcome email and FAQ steps as they are, and rework only the checklist step for remote-specific logistics — most of the workflow still applies.', 24, 'advanced', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'finance',
 'What could a monthly reporting workflow with Claude include end-to-end?', 'Summarize the raw numbers, draft the variance commentary, then format the executive summary — connected steps building toward the finished report.', 25, 'beginner', 'concept'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'finance',
 'You want Claude to summarize this month''s figures, then explain the variances, then write an executive summary — one after another.', 'Treat it as a workflow and check the number summary for accuracy first — the variance commentary and executive summary both depend on it, so an early error would carry through the rest.', 26, 'intermediate', 'scenario'),
((select id from public.flashcard_decks where module_id=(select id from public.modules where slug='workflows')), 'finance',
 'Your close-reporting workflow (summarize, variance commentary, exec summary) works well, but the board version needs a different exec-summary step.', 'Keep the summarize and variance-commentary steps unchanged, and adapt only the exec-summary step''s tone and depth for the board audience — most of the workflow transfers directly.', 27, 'advanced', 'scenario');

commit;
