-- ============================================================================
-- Gyaan LMS — Seed data, chunk 3 of 3 (run these AFTER the schema migrations,
-- in order 1 -> 2 -> 3). Split out because the combined file is large enough
-- that some browser-based SQL editors can silently truncate a single paste.
-- ============================================================================

begin;

-- ===========================================================================
-- QUIZ QUESTIONS  (27 per module: 9 generic across 3 difficulty tiers + 3 per profession x 6)
-- ===========================================================================

-- ---- chat-basics ----
insert into public.quiz_questions (module_id, profession, question, options, correct_index, explanation, difficulty, kind, hint, order_index) values
((select id from public.modules where slug='chat-basics'), null,
 'In a Claude conversation, what does Claude use to generate each new reply?',
 '["The full message history in that conversation", "Only your most recent message", "A saved profile of your preferences", "The title you gave the chat"]'::jsonb,
 0, 'Claude reads the whole conversation so far — not just your latest message — to generate a reply that fits the context.',
 'beginner', 'mcq', 'Think about how much of the conversation Claude actually re-reads each turn.', 1),
((select id from public.modules where slug='chat-basics'), null,
 'Starting a new chat with Claude gives you a completely fresh conversation with no memory of your other chats.',
 '["True", "False"]'::jsonb,
 0, 'Each new chat begins with a clean slate — Claude has no access to other conversations unless you paste that information in.',
 'beginner', 'true_false', 'Consider whether separate chats are linked to one another.', 2),
((select id from public.modules where slug='chat-basics'), null,
 'You ask Claude to write a short bio, then reply "make it more casual" in the same chat — what happens?',
 '["Claude revises the bio it already wrote, using the casual-tone feedback", "Claude asks you to repaste the original bio", "Claude ignores the request since it''s a new topic", "Claude starts an entirely unrelated new bio"]'::jsonb,
 0, 'Because the follow-up is in the same conversation, Claude can see the earlier draft and revise it directly.',
 'beginner', 'scenario', 'Remember that everything earlier in the same chat is still visible to Claude.', 3),
((select id from public.modules where slug='chat-basics'), null,
 'The running history of messages that Claude reads before generating each reply is called the _____.',
 '["context window", "chat title", "system log", "memory bank"]'::jsonb,
 0, '"Context window" is the term for the conversation history Claude actively reads and reasons over.',
 'intermediate', 'fill_blank', 'This is the same idea as "how far back Claude can see."', 4),
((select id from public.modules where slug='chat-basics'), null,
 'Why is it often better to correct a draft with a follow-up message than to retype the whole request?',
 '["The follow-up builds on the existing draft and context, so Claude can make a targeted edit", "Claude charges less for follow-up messages", "Retyping the request deletes the chat", "Follow-ups always produce a completely different answer"]'::jsonb,
 0, 'A follow-up message lets Claude reuse everything already established in the chat, so it can make a precise, targeted change.',
 'intermediate', 'mcq', 'Think about what Claude can still see when you send a short correction.', 5),
((select id from public.modules where slug='chat-basics'), null,
 'If you want Claude to remember details from a conversation you had yesterday in a different chat, it will automatically recall them in today''s new chat.',
 '["True", "False"]'::jsonb,
 1, 'Conversations don''t share memory by default — you''d need to paste in the relevant details yourself.',
 'intermediate', 'true_false', 'Ask whether chats are connected behind the scenes.', 6),
((select id from public.modules where slug='chat-basics'), null,
 'After 80 messages debating a marketing plan, Claude suggests an option the team explicitly ruled out 50 messages earlier. What''s the most likely cause, and best fix?',
 '["The thread has grown long enough that earlier turns are getting crowded out \u2014 summarize the decisions and start fresh", "Claude is deliberately testing the team''s patience", "The chat has a bug and needs to be deleted", "Claude cannot ever forget anything, so this must be a misunderstanding"]'::jsonb,
 0, 'Very long threads can dilute or push out earlier context. Recapping key decisions in a fresh chat restores a clean, reliable footing.',
 'advanced', 'scenario', 'Think about what happens to older turns once a conversation grows very large.', 7),
((select id from public.modules where slug='chat-basics'), null,
 'When a chat has drifted off-track after many messages, the most reliable fix is often to write a short _____ of what''s been decided and start a new conversation.',
 '["summary", "apology", "transcript", "attachment"]'::jsonb,
 0, 'A concise summary of decisions and constraints gives the new chat clean, accurate context to work from.',
 'advanced', 'fill_blank', 'Think about what you''d hand someone joining the project midway.', 8),
((select id from public.modules where slug='chat-basics'), null,
 'What''s the real trade-off between continuing one very long chat versus starting a new one?',
 '["Long chats keep rich shared context but risk drift and dilution \u2014 new chats are clean but need context rebuilt manually", "Long chats are always worse and should never be used", "New chats automatically inherit all prior context, so there''s no trade-off", "Chat length has no effect on answer quality"]'::jsonb,
 0, 'Both approaches have real costs — a long thread can lose sharpness, while a new one starts blank — so the right choice depends on the situation.',
 'advanced', 'mcq', 'Weigh what you keep and what you lose in each approach.', 9),
((select id from public.modules where slug='chat-basics'), 'recruitment',
 'You''re using Claude to write a candidate outreach message. What''s the best first step?',
 '["Give Claude the role, candidate background, and tone you want, then refine in follow-ups", "Ask Claude to guess everything without any details", "Only tell Claude the company name", "Send the message before reviewing it"]'::jsonb,
 0, 'Starting with real specifics gives Claude something concrete to work from, and you can refine from there.',
 'beginner', 'mcq', 'Think about what makes a first draft useful versus generic.', 10),
((select id from public.modules where slug='chat-basics'), 'recruitment',
 'A recruiter asks Claude for a job description, then in the same chat says "add a benefits section." What does Claude do?',
 '["Adds the benefits section to the existing draft, since it can see the conversation so far", "Writes a brand-new job description from scratch", "Asks the recruiter to repaste the whole draft", "Ignores the request since it''s unrelated to hiring"]'::jsonb,
 0, 'Because it''s the same chat, Claude edits the draft it already produced rather than starting over.',
 'intermediate', 'scenario', 'Consider what Claude can still see from earlier in this thread.', 11),
((select id from public.modules where slug='chat-basics'), 'recruitment',
 'When screening many candidates in one long Claude chat, keeping everyone''s notes in a single thread is always the most reliable approach.',
 '["True", "False"]'::jsonb,
 1, 'Very long threads with many candidates can blur together — splitting into separate chats per candidate or batch keeps context accurate.',
 'advanced', 'true_false', 'Think about what happens to accuracy as a single thread gets crowded with many similar cases.', 12),
((select id from public.modules where slug='chat-basics'), 'marketing',
 'If Claude''s first draft of a social post isn''t in your brand voice, the fastest fix is to reply in the same chat and describe the _____ you want.',
 '["tone", "font", "hashtag count", "file format"]'::jsonb,
 0, 'Describing the tone you want lets Claude revise the existing draft directly.',
 'beginner', 'fill_blank', 'Think about what aspect of writing style you''d actually be correcting.', 13),
((select id from public.modules where slug='chat-basics'), 'marketing',
 'Why does sending several small follow-up corrections often work better than trying to write one perfect prompt for a campaign brief?',
 '["Each correction builds on the previous draft and context Claude already has", "Claude gives better answers only after the tenth message", "Follow-ups reset the conversation, giving a cleaner result", "Perfect prompts are impossible to write for marketing tasks"]'::jsonb,
 0, 'Iterating lets you refine gradually, and Claude uses everything already established in the thread.',
 'intermediate', 'mcq', 'Think about what a follow-up message can build on that a brand-new prompt can''t.', 14),
((select id from public.modules where slug='chat-basics'), 'marketing',
 'Fifty messages into a campaign brainstorm, Claude re-suggests an idea the team rejected early on. What should the marketer do?',
 '["Summarize the current direction and firm rejections, then continue in a new chat", "Keep repeating the rejection in every message forever", "Assume Claude is malfunctioning and stop using it", "Delete the chat with no summary and start blind"]'::jsonb,
 0, 'A clean recap in a new chat restores the important decisions without the clutter of a long thread.',
 'advanced', 'scenario', 'Think about what carries forward reliably versus what tends to get buried in a long thread.', 15),
((select id from public.modules where slug='chat-basics'), 'sales',
 'What should you give Claude before asking it to draft sales call talking points?',
 '["Who the prospect is, what they do, and your goal for the call", "Nothing \u2014 Claude works best with no context", "Only the prospect''s name", "The entire company''s annual report"]'::jsonb,
 0, 'Concrete, relevant context lets Claude produce talking points that actually fit the call.',
 'beginner', 'mcq', 'Think about what information turns a generic outline into a useful one.', 16),
((select id from public.modules where slug='chat-basics'), 'sales',
 'Once you''ve discussed a deal at length in one chat, asking Claude to "now draft the follow-up email" will reuse the context already in that conversation.',
 '["True", "False"]'::jsonb,
 0, 'Because it''s the same chat, Claude can pull from everything already discussed about the deal.',
 'intermediate', 'true_false', 'Consider what''s still visible to Claude within a single ongoing conversation.', 17),
((select id from public.modules where slug='chat-basics'), 'sales',
 'You want to start a new chat about a deal you discussed extensively last week. What''s the best way to avoid Claude starting cold?',
 '["Paste a short recap of the deal stage, key objections, and next step as your opening message", "Assume Claude remembers last week''s chat automatically", "Re-explain the entire company history in exhaustive detail", "Avoid giving any context so Claude isn''t biased"]'::jsonb,
 0, 'A concise recap gives the new chat the essential context without dragging in an old, possibly cluttered thread.',
 'advanced', 'scenario', 'Think about what a colleague would need to get up to speed quickly.', 18),
((select id from public.modules where slug='chat-basics'), 'engineering',
 'You tried a fix Claude suggested and it didn''t work. What''s the best next step?',
 '["Reply in the same chat describing what happened when you tried it", "Start a brand-new chat with no context", "Assume the bug is unfixable", "Ask an unrelated question instead"]'::jsonb,
 0, 'Replying in the same thread lets Claude see the original error and its own suggestion, so it can adjust.',
 'beginner', 'mcq', 'Think about what information helps Claude improve its next attempt.', 19),
((select id from public.modules where slug='chat-basics'), 'engineering',
 'Starting a separate chat for an unrelated formatting question, instead of adding it to your debugging thread, helps keep each conversation''s _____ focused.',
 '["context", "file size", "font", "username"]'::jsonb,
 0, 'Keeping unrelated topics in separate chats avoids diluting each thread''s context with irrelevant details.',
 'intermediate', 'fill_blank', 'Think about what gets muddied when unrelated topics share one conversation.', 20),
((select id from public.modules where slug='chat-basics'), 'engineering',
 'In a 60-message pair-programming chat, Claude proposes a fix that ignores a constraint you mentioned early on. What''s the best move?',
 '["Restate the key constraint, or start a fresh chat with a short spec summarizing the constraints", "Give up on using Claude for this task", "Assume the constraint no longer matters", "Keep repeating the same full request from scratch each time"]'::jsonb,
 0, 'Long threads can crowd out earlier specifics — restating constraints, or resetting with a clean summary, keeps them front and center.',
 'advanced', 'scenario', 'Think about how easy it is for a detail to get buried after dozens of messages.', 21),
((select id from public.modules where slug='chat-basics'), 'hr',
 'What''s a good low-risk first task for a new Claude chat in HR work?',
 '["Drafting something routine, like an onboarding checklist, then refining it together", "Immediately finalizing a sensitive termination letter with no review", "Asking Claude to make final legal decisions", "Skipping review of anything Claude drafts"]'::jsonb,
 0, 'Routine, low-stakes drafts are a great way to get comfortable iterating with Claude before tackling sensitive material.',
 'beginner', 'mcq', 'Think about what kind of task is safe to practice on.', 22),
((select id from public.modules where slug='chat-basics'), 'hr',
 'Telling Claude "keep everything the same but make section 2 more concise" will cause it to rewrite the entire document from scratch.',
 '["True", "False"]'::jsonb,
 1, 'A precise, targeted instruction lets Claude revise just the part you asked about, not the whole document.',
 'intermediate', 'true_false', 'Think about what a specific instruction lets Claude leave untouched.', 23),
((select id from public.modules where slug='chat-basics'), 'hr',
 'While drafting a sensitive policy update across a long chat, Claude''s latest version quietly drops a caveat you added earlier. What should you do?',
 '["Re-state the caveat explicitly and do a full read-through before finalizing anything sensitive", "Trust the latest version completely without checking", "Assume Claude removed it intentionally for a good reason", "Abandon the chat and never mention the caveat again"]'::jsonb,
 0, 'Long threads can lose track of earlier specific instructions, so sensitive material deserves a careful final review.',
 'advanced', 'scenario', 'Think about what''s easy to lose track of in a long, evolving draft.', 24),
((select id from public.modules where slug='chat-basics'), 'finance',
 'You asked Claude to summarize a budget memo and want it shorter. What should you do?',
 '["Ask in the same chat for a shorter version \u2014 Claude will condense what it already wrote", "Paste the entire memo again from scratch", "Open a new chat with no context", "Give up, since summaries can''t be revised"]'::jsonb,
 0, 'Claude can see its own earlier summary in the thread and shorten it directly.',
 'beginner', 'mcq', 'Think about what Claude still has access to from earlier in the conversation.', 25),
((select id from public.modules where slug='chat-basics'), 'finance',
 'Telling Claude your audience early in a chat (e.g., "this is for the board") is useful because that framing _____ through the rest of the conversation.',
 '["carries", "disappears", "conflicts", "resets"]'::jsonb,
 0, 'Once established, that context applies to later drafts and revisions without needing to be repeated.',
 'intermediate', 'fill_blank', 'Think about whether early details stay relevant as the chat continues.', 26),
((select id from public.modules where slug='chat-basics'), 'finance',
 'You''ve built a detailed forecast discussion over many messages and need to share the key assumptions with a colleague who wasn''t in the chat. What''s the best move?',
 '["Ask Claude, in that same thread, to summarize the finalized assumptions into a clean standalone recap", "Forward the entire raw chat transcript with no summary", "Ask the colleague to redo the analysis independently", "Assume the colleague doesn''t need any context"]'::jsonb,
 0, 'A focused summary turns a long working conversation into something clear and shareable, without you re-deriving it manually.',
 'advanced', 'scenario', 'Think about what''s actually useful to hand someone who wasn''t part of the process.', 27);

-- ---- prompting ----
insert into public.quiz_questions (module_id, profession, question, options, correct_index, explanation, difficulty, kind, hint, order_index) values
((select id from public.modules where slug='prompting'), null,
 'Which prompt is more likely to get a useful first draft?',
 '["Write a 3-paragraph product update email for existing customers, friendly tone, mentioning the new dashboard feature", "Write an email", "Make something good", "Do the email thing"]'::jsonb,
 0, 'The specific prompt states format, length, audience, tone, and content — everything Claude needs to know what "good" means here.',
 'beginner', 'mcq', 'Compare how much each option actually tells Claude about what you want.', 1),
((select id from public.modules where slug='prompting'), null,
 'Adding more adjectives like "great" or "amazing" to a prompt reliably improves Claude''s output.',
 '["True", "False"]'::jsonb,
 1, 'Vague adjectives are subjective and don''t tell Claude what to prioritize — concrete details like audience, format, and length do far more work.',
 'beginner', 'true_false', 'Think about whether an adjective actually specifies anything Claude can act on.', 2),
((select id from public.modules where slug='prompting'), null,
 'You want Claude to write in the voice of a specific expert. What technique are you using?',
 '["Role prompting", "Few-shot prompting", "Chain-of-thought prompting", "Zero-shot prompting"]'::jsonb,
 0, 'Asking Claude to respond as a particular persona or expert is role prompting.',
 'beginner', 'scenario', 'Think about what you''re asking Claude to pretend to be.', 3),
((select id from public.modules where slug='prompting'), null,
 'Showing Claude one or two examples of the exact output style you want, rather than describing it in words, is called _____ prompting.',
 '["few-shot", "zero-shot", "role-based", "open-ended"]'::jsonb,
 0, 'Few-shot prompting means providing examples ("shots") of the desired pattern.',
 'intermediate', 'fill_blank', 'The term counts how many examples you''re giving.', 4),
((select id from public.modules where slug='prompting'), null,
 'Why does specifying the audience for a piece of writing usually improve Claude''s output?',
 '["It narrows down vocabulary, depth, and tone to what actually fits that reader", "It has no effect on the output", "It only matters for very long documents", "It replaces the need for any other instructions"]'::jsonb,
 0, 'Audience context shapes word choice, depth, and framing — all things that determine whether the writing actually lands.',
 'intermediate', 'mcq', 'Think about how differently you''d explain the same idea to two different readers.', 5),
((select id from public.modules where slug='prompting'), null,
 'A role prompt (e.g., "respond as a data analyst") can change what Claude focuses on, not just its tone.',
 '["True", "False"]'::jsonb,
 0, 'A role shifts priorities and areas of focus, not just word choice — a "data analyst" role emphasizes different things than a "marketing writer" role would.',
 'intermediate', 'true_false', 'Consider whether a persona changes more than just the writing style.', 6),
((select id from public.modules where slug='prompting'), null,
 'You''ve given Claude a role, format instructions, and one example, but the tone still misses the mark. What''s the most likely fix?',
 '["Check whether the example itself actually demonstrates the tone you want \u2014 examples tend to carry more weight than written instructions", "Add even more adjectives describing the tone", "Remove the role instruction entirely", "Give up on using an example"]'::jsonb,
 0, 'Concrete examples strongly influence output — if the example doesn''t match the tone you''re asking for, it can override the written instruction.',
 'advanced', 'scenario', 'Think about which part of the prompt Claude is most likely to closely imitate.', 7),
((select id from public.modules where slug='prompting'), null,
 'Stacking a role, relevant context, and one or more examples together in a single prompt is sometimes called _____ prompting.',
 '["layered", "zero-shot", "single-pass", "blind"]'::jsonb,
 0, 'Layered prompting combines multiple techniques — role, context, and examples — for a more reliable result than relying on just one.',
 'advanced', 'fill_blank', 'Think about what''s happening when several techniques are combined at once.', 8),
((select id from public.modules where slug='prompting'), null,
 'When is few-shot prompting most worth the extra effort of writing an example?',
 '["When the output needs a specific style or structure that''s hard to fully describe in words", "For every single prompt, regardless of task", "Only when writing code, never for prose", "Never \u2014 descriptions are always sufficient"]'::jsonb,
 0, 'Examples shine when nuance or structure is hard to put into words — a concrete pattern communicates it more reliably.',
 'advanced', 'mcq', 'Think about tasks where describing "the right feel" in words is genuinely difficult.', 9),
((select id from public.modules where slug='prompting'), 'recruitment',
 'Which detail would make a job-description prompt most specific?',
 '["The exact role, seniority level, and must-have skills", "Just the word \"developer\"", "No details at all", "The company''s stock price"]'::jsonb,
 0, 'Concrete role details are what let Claude write a description that actually fits the position.',
 'beginner', 'mcq', 'Think about what a hiring manager would need to know to write this well.', 10),
((select id from public.modules where slug='prompting'), 'recruitment',
 'Outreach messages to five candidates all come out generic and interchangeable. What''s the fix?',
 '["Give Claude each candidate''s specific background and what drew you to their profile", "Ask Claude to write faster", "Send the same message to everyone anyway", "Remove all details to keep it simple"]'::jsonb,
 0, 'Specific, individual context is what makes outreach feel personalized rather than templated.',
 'intermediate', 'scenario', 'Think about what actually differs between five real candidates.', 11),
((select id from public.modules where slug='prompting'), 'recruitment',
 'Pasting one completed interview scorecard as an example is likely to match your team''s exact format more reliably than describing the format in a paragraph.',
 '["True", "False"]'::jsonb,
 0, 'A concrete example (few-shot) communicates exact structure and detail level more reliably than a written description.',
 'advanced', 'true_false', 'Think about which communicates a precise format more faithfully — words or a worked sample.', 12),
((select id from public.modules where slug='prompting'), 'marketing',
 'What is a "role" prompt in a marketing context?',
 '["Asking Claude to write as a specific persona, like a witty social media manager for a sneaker brand", "Asking Claude to summarize a role posting", "Giving Claude no instructions at all", "Asking for a list of job roles"]'::jsonb,
 0, 'A role prompt asks Claude to adopt a persona, shaping tone and priorities to match.',
 'beginner', 'mcq', 'Think about what you''re asking Claude to pretend to be.', 13),
((select id from public.modules where slug='prompting'), 'marketing',
 'Pasting three of your brand''s best-performing headlines before asking for new ones is an example of _____ prompting.',
 '["few-shot", "zero-shot", "role-based", "blind"]'::jsonb,
 0, 'Providing real examples of the pattern you want is few-shot prompting.',
 'intermediate', 'fill_blank', 'Think about the Project feature designed to hold reusable reference files.', 14),
((select id from public.modules where slug='prompting'), 'marketing',
 'Claude''s ad copy matches your brand''s tone but keeps missing the audience''s actual pain points. What''s missing from the prompt?',
 '["Audience context \u2014 who they are and what problem they''re trying to solve", "More adjectives describing the tone", "A stricter word count", "A different persona"]'::jsonb,
 0, 'Tone alone doesn''t convey what the audience actually cares about — that requires explicit audience context.',
 'advanced', 'scenario', 'Think about what''s different between "sounding right" and "speaking to the right problem."', 15),
((select id from public.modules where slug='prompting'), 'sales',
 'Why is "write a follow-up email to a prospect" a weak prompt?',
 '["It''s missing who the prospect is, what was discussed, and the desired next step", "It''s too long", "It uses the word \"prospect\"", "It doesn''t mention pricing"]'::jsonb,
 0, 'Without those specifics, Claude has to guess at details that determine whether the email is actually useful.',
 'beginner', 'mcq', 'Think about what information a real rep would need before writing this email.', 16),
((select id from public.modules where slug='prompting'), 'sales',
 'Telling Claude to "respond as a sales coach reviewing this pitch" is an example of role prompting.',
 '["True", "False"]'::jsonb,
 0, 'Assigning Claude a persona — here, a sales coach — is exactly what role prompting means.',
 'intermediate', 'true_false', 'Consider what kind of instruction this is.', 17),
((select id from public.modules where slug='prompting'), 'sales',
 'You want objection-handling replies that are direct but never pushy, matching your team''s style. What''s the most reliable approach?',
 '["Give Claude two or three real examples of your team''s best objection responses", "Just say \"be direct but not pushy\" and nothing else", "Ask for ten different tones and pick one later", "Avoid giving any examples so Claude isn''t biased"]'::jsonb,
 0, 'Concrete examples teach a nuanced balance like "direct but not pushy" more reliably than an abstract description.',
 'advanced', 'scenario', 'Think about how hard "direct but not pushy" is to fully capture in a short instruction.', 18),
((select id from public.modules where slug='prompting'), 'engineering',
 'What makes a code-request prompt specific?',
 '["Naming the language, exact inputs/outputs, and any constraints", "Just saying \"write a function\"", "Leaving out the programming language", "Asking for \"something efficient\" with no other detail"]'::jsonb,
 0, 'Concrete technical details are what let Claude produce code that actually fits your needs.',
 'beginner', 'mcq', 'Think about what a teammate would need to know to write this function correctly.', 19),
((select id from public.modules where slug='prompting'), 'engineering',
 'Asking Claude to review code "as a senior reviewer, focus only on performance and edge cases" is an example of _____ prompting.',
 '["role", "few-shot", "zero-shot", "format-only"]'::jsonb,
 0, 'Assigning a persona and focus area is role prompting — it narrows what Claude pays attention to.',
 'intermediate', 'fill_blank', 'Think about what kind of persona you''re asking Claude to take on.', 20),
((select id from public.modules where slug='prompting'), 'engineering',
 'You want Claude to write a new function that matches your team''s exact style conventions. What''s the most reliable approach?',
 '["Show it one function you''ve already written in that style as a few-shot example", "Describe your style guide in a single adjective like \"clean\"", "Avoid mentioning style at all", "Ask for the function in every possible style and pick the best"]'::jsonb,
 0, 'A concrete code example transmits style conventions — naming, structure, comments — more precisely than a description can.',
 'advanced', 'scenario', 'Think about what communicates coding style more precisely — words or a real sample.', 21),
((select id from public.modules where slug='prompting'), 'hr',
 'Why is "write a policy" too vague a prompt on its own?',
 '["It doesn''t say which policy, for what situation, or in what tone", "It''s grammatically incorrect", "It''s too short to be a real prompt", "Claude cannot write policies at all"]'::jsonb,
 0, 'Without those specifics, Claude has to guess at context that determines what a useful answer looks like.',
 'beginner', 'mcq', 'Think about how many different "policies" this could mean.', 22),
((select id from public.modules where slug='prompting'), 'hr',
 'Asking Claude to "respond as an employee relations specialist" only changes its tone, not what it focuses on.',
 '["True", "False"]'::jsonb,
 1, 'A role prompt shifts focus and priorities too — an employee relations specialist would emphasize fairness and compliance, not just sound a certain way.',
 'intermediate', 'true_false', 'Consider whether a persona changes more than just word choice.', 23),
((select id from public.modules where slug='prompting'), 'hr',
 'You need several FAQ answers in your company''s exact voice, but describing that voice in words keeps falling short. What should you do?',
 '["Paste two or three existing FAQ answers as few-shot examples", "Use stronger adjectives like \"very friendly\"", "Ask Claude to guess your company''s voice", "Give up and write them yourself with no AI help"]'::jsonb,
 0, 'Concrete examples transmit voice and structure more precisely than adjectives ever can.',
 'advanced', 'scenario', 'Think about what communicates a specific tone more reliably — a description or a real sample.', 24),
((select id from public.modules where slug='prompting'), 'finance',
 'What''s missing from the prompt "summarize this report"?',
 '["The audience, desired length, and what to emphasize", "The word \"report\"", "A greeting", "The file format"]'::jsonb,
 0, 'Those details determine what a genuinely useful summary looks like for this reader.',
 'beginner', 'mcq', 'Think about what changes a "good summary" from one reader to the next.', 25),
((select id from public.modules where slug='prompting'), 'finance',
 'Telling Claude "explain this like you''re briefing a first-time investor with no finance background" is an example of _____ prompting.',
 '["role", "few-shot", "zero-shot", "blind"]'::jsonb,
 0, 'Framing the audience/persona this way is role prompting — it adjusts vocabulary and depth accordingly.',
 'intermediate', 'fill_blank', 'Think about what persona or audience you''re describing here.', 26),
((select id from public.modules where slug='prompting'), 'finance',
 'You want variance-analysis commentary that matches your finance team''s exact structure. What''s the most reliable approach?',
 '["Provide one completed example of the commentary format as a few-shot example", "Describe \"our usual format\" in one sentence", "Skip formatting instructions entirely", "Ask for five different formats and merge them"]'::jsonb,
 0, 'A concrete example is far more reliable than a verbal description for conveying an exact structural format.',
 'advanced', 'scenario', 'Think about what communicates an exact structure more precisely — words or a worked sample.', 27);

-- ---- projects ----
insert into public.quiz_questions (module_id, profession, question, options, correct_index, explanation, difficulty, kind, hint, order_index) values
((select id from public.modules where slug='projects'), null,
 'What is a Claude Project?',
 '["A dedicated space with custom instructions and shared knowledge available to every chat inside it", "A single very long conversation", "A way to delete old chats", "A setting that changes Claude''s writing speed"]'::jsonb,
 0, 'A Project bundles standing instructions and reference material that every chat within it can draw on.',
 'beginner', 'mcq', 'Think about what''s shared across multiple chats, rather than living in just one.', 1),
((select id from public.modules where slug='projects'), null,
 'Custom instructions set in a Project automatically apply to every new chat started inside that Project.',
 '["True", "False"]'::jsonb,
 0, 'That''s the point of custom instructions — they''re standing guidance applied across the Project''s conversations.',
 'beginner', 'true_false', 'Consider what "standing instructions" implies about future chats.', 2),
((select id from public.modules where slug='projects'), null,
 'You upload your company''s style guide to a Project instead of pasting it into every chat. What are you using?',
 '["Project knowledge", "A new custom model", "A chat title", "A saved reply"]'::jsonb,
 0, 'Reference files added to a Project are its project knowledge — available to every chat inside it.',
 'beginner', 'scenario', 'Think about what category of Project feature holds reference documents.', 3),
((select id from public.modules where slug='projects'), null,
 'Setting up a Project''s instructions and knowledge once, so every future chat automatically has that context, is called _____ context.',
 '["persistent", "temporary", "hidden", "exported"]'::jsonb,
 0, 'Persistent context sticks around across every chat in the Project, unlike context in a single conversation.',
 'intermediate', 'fill_blank', 'Think of a word meaning "lasting" or "carried forward."', 4),
((select id from public.modules where slug='projects'), null,
 'What''s the main time-saving benefit of using a Project for recurring work?',
 '["You set up background and preferences once instead of re-explaining them in every new chat", "Projects make Claude respond faster", "Projects automatically write your final answer for you", "Projects remove the need to review any output"]'::jsonb,
 0, 'The core benefit is not re-typing the same context every time — it''s already there for every chat in the Project.',
 'intermediate', 'mcq', 'Think about what you''d otherwise have to repeat in every fresh chat.', 5),
((select id from public.modules where slug='projects'), null,
 'Updating a Project''s knowledge files retroactively changes the answers Claude already gave in old chats within that Project.',
 '["True", "False"]'::jsonb,
 1, 'Updated knowledge affects future chats going forward — it doesn''t rewrite responses that were already given.',
 'intermediate', 'true_false', 'Consider whether a knowledge update reaches backward or only forward in time.', 6),
((select id from public.modules where slug='projects'), null,
 'A Project''s knowledge base has grown large with some outdated files still mixed in. What''s the risk?',
 '["Outdated material can crowd out what''s relevant and lead to answers based on stale information", "There''s no risk \u2014 more knowledge is always strictly better", "Claude will automatically ignore anything old", "The Project will stop working entirely"]'::jsonb,
 0, 'A cluttered, unpruned knowledge base can cause Claude to draw on outdated or conflicting material instead of what''s current.',
 'advanced', 'scenario', 'Think about what happens when old and new reference material sit side by side.', 7),
((select id from public.modules where slug='projects'), null,
 'The risk of a Project''s reference material becoming outdated and degrading answer quality is sometimes called knowledge _____.',
 '["staleness", "expansion", "encryption", "duplication"]'::jsonb,
 0, '"Knowledge staleness" describes outdated reference material quietly undermining the quality of Claude''s answers.',
 'advanced', 'fill_blank', 'Think of a word describing food or information that''s gone past its useful date.', 8),
((select id from public.modules where slug='projects'), null,
 'A Project defaults to a formal tone, but one chat needs something more casual. What should you do?',
 '["State the override explicitly in that chat \u2014 in-conversation instructions take precedence for that conversation", "Nothing can be done \u2014 the Project''s tone is locked forever", "Delete the Project and start over", "Create an entirely new account"]'::jsonb,
 0, 'An explicit in-chat instruction generally overrides the Project''s standing default for that specific conversation.',
 'advanced', 'mcq', 'Think about which instruction is more specific and recent — the Project default or what you just typed.', 9),
((select id from public.modules where slug='projects'), 'recruitment',
 'What might a recruiter store as project knowledge in a Project?',
 '["Outreach templates and the company''s tone-of-voice guide", "Random unrelated files", "Nothing \u2014 Projects can''t hold files", "Only candidate resumes with no other context"]'::jsonb,
 0, 'Reusable reference material like templates and style guides is exactly what project knowledge is for.',
 'beginner', 'mcq', 'Think about what a recruiter re-uses across many candidate conversations.', 10),
((select id from public.modules where slug='projects'), 'recruitment',
 'Explaining your company''s interview process once in a Project''s custom instructions means every future chat in that Project already knows it.',
 '["True", "False"]'::jsonb,
 0, 'Custom instructions apply automatically to every chat inside that Project, so it doesn''t need to be re-explained.',
 'intermediate', 'true_false', 'Consider what "custom instructions" are designed to do across chats.', 11),
((select id from public.modules where slug='projects'), 'recruitment',
 'A Hiring Project''s knowledge includes an outdated job-leveling guide replaced last quarter. What should the recruiter do?',
 '["Remove or update the outdated file so Claude doesn''t apply old criteria", "Leave it \u2014 old and new guides rarely conflict", "Delete the whole Project", "Ignore it since Claude won''t reference old files"]'::jsonb,
 0, 'Stale reference material can cause Claude to apply criteria that no longer match current standards.',
 'advanced', 'scenario', 'Think about what happens when outdated and current guidance sit in the same knowledge base.', 12),
((select id from public.modules where slug='projects'), 'marketing',
 'What''s a natural use of a Project for a marketing team?',
 '["A \"Brand Voice\" Project holding style guides and past campaigns", "A Project with no files or instructions at all", "A single chat used for everything, including unrelated tasks", "A Project that only stores images"]'::jsonb,
 0, 'Centralizing brand reference material in a Project keeps every content request consistent with brand voice.',
 'beginner', 'mcq', 'Think about what marketing content needs to stay consistent across many requests.', 13),
((select id from public.modules where slug='projects'), 'marketing',
 'Uploading brand guidelines once into a Project instead of pasting them into every content chat is an example of using _____.',
 '["project knowledge", "a new device", "a chat export", "a browser extension"]'::jsonb,
 0, 'Project knowledge is exactly this — persistent reference material shared across the Project''s chats.',
 'intermediate', 'fill_blank', 'Think about the Project feature designed to hold reusable reference files.', 14),
((select id from public.modules where slug='projects'), 'marketing',
 'A Campaigns Project defaults to a bold, energetic voice, but this week''s brief needs a somber, empathetic tone. What''s the best move?',
 '["State the tone override explicitly in that chat", "Create an entirely new account for this one brief", "Wait for the Project''s default to change on its own", "Ignore the mismatch and use the bold voice anyway"]'::jsonb,
 0, 'An explicit in-chat instruction takes precedence over the Project''s standing tone default for that conversation.',
 'advanced', 'scenario', 'Think about which is more specific to this one task — the Project default or what you type now.', 15),
((select id from public.modules where slug='projects'), 'sales',
 'What could a sales rep store in a "Deal Prep" Project?',
 '["Product one-pagers and objection-handling notes", "Nothing relevant to sales", "Random personal files", "Only email signatures"]'::jsonb,
 0, 'Reusable sales reference material is exactly what project knowledge is designed to hold.',
 'beginner', 'mcq', 'Think about what a rep re-uses across many different deals.', 16),
((select id from public.modules where slug='projects'), 'sales',
 'A Project lets you start a fresh chat per account while still sharing common reference material like product info across all of them.',
 '["True", "False"]'::jsonb,
 0, 'That''s a key benefit of Projects — clean per-chat context combined with shared background knowledge.',
 'intermediate', 'true_false', 'Consider what stays shared versus what starts fresh with each new chat in a Project.', 17),
((select id from public.modules where slug='projects'), 'sales',
 'An Enterprise Deals Project''s knowledge still lists pricing from two quarters ago. What''s the risk?',
 '["Claude might produce proposals or talking points based on outdated numbers", "No risk \u2014 Claude always uses the latest public pricing automatically", "The Project will refuse to function", "Old pricing files are automatically deleted"]'::jsonb,
 0, 'Outdated reference material in project knowledge can silently feed into current work unless it''s updated.',
 'advanced', 'scenario', 'Think about what happens when Claude has no way to know the pricing file is stale.', 18),
((select id from public.modules where slug='projects'), 'engineering',
 'What might an engineer add to a Project''s knowledge for a specific codebase?',
 '["Architecture notes and coding conventions", "Nothing \u2014 Projects don''t support technical files", "Random unrelated screenshots", "Only the final compiled binary"]'::jsonb,
 0, 'Technical reference material like architecture notes is exactly what project knowledge is designed for.',
 'beginner', 'mcq', 'Think about what context a new teammate would need about this codebase.', 19),
((select id from public.modules where slug='projects'), 'engineering',
 'Adding a style guide once as project knowledge instead of pasting it into every new chat is an example of _____ context.',
 '["persistent", "one-time", "hidden", "exported"]'::jsonb,
 0, 'Persistent context is set up once and remains available across every chat in the Project.',
 'intermediate', 'fill_blank', 'Think of a word meaning "sticks around" across future chats.', 20),
((select id from public.modules where slug='projects'), 'engineering',
 'A team''s Project knowledge includes a deprecated API''s docs alongside the current API''s docs. What''s the risk?',
 '["Claude may mix guidance from the old and new APIs, producing subtly broken suggestions", "There''s no risk since Claude always prefers the newest file", "The deprecated docs will be auto-deleted", "The Project will crash"]'::jsonb,
 0, 'Conflicting reference material can lead to suggestions that blend outdated and current guidance.',
 'advanced', 'scenario', 'Think about what happens when two versions of the same reference disagree.', 21),
((select id from public.modules where slug='projects'), 'hr',
 'What''s a good use of a Project for HR?',
 '["An \"Employee Policies\" Project holding the current handbook", "A Project with no organizing theme at all", "Storing only employees'' personal contact info", "A Project used for one single unrelated chat"]'::jsonb,
 0, 'Centralizing current policy documents keeps answers consistent across every policy-related chat.',
 'beginner', 'mcq', 'Think about what needs to stay consistent when many people ask policy questions.', 22),
((select id from public.modules where slug='projects'), 'hr',
 'Every chat inside an HR Project can reference the same up-to-date handbook without it being re-uploaded each time.',
 '["True", "False"]'::jsonb,
 0, 'That''s the point of project knowledge — one upload, available to every chat in that Project.',
 'intermediate', 'true_false', 'Consider what "shared" reference material implies about needing to re-upload.', 23),
((select id from public.modules where slug='projects'), 'hr',
 'An Onboarding Project defaults to a warm, welcoming tone, but this week you''re drafting a formal compliance notice. What should you do?',
 '["Explicitly state the tone you need for that specific chat", "Nothing \u2014 the default tone can never be changed", "Create a brand-new account just for this notice", "Delete the Project''s custom instructions permanently"]'::jsonb,
 0, 'An in-chat instruction overrides the Project''s default tone just for that one conversation.',
 'advanced', 'scenario', 'Think about which instruction is more specific — the standing default or what you type right now.', 24),
((select id from public.modules where slug='projects'), 'finance',
 'What could a finance team store as project knowledge in a "Monthly Close" Project?',
 '["The chart of accounts and prior month templates", "Nothing \u2014 finance data shouldn''t go in Projects", "Only a list of employee names", "Random unrelated spreadsheets"]'::jsonb,
 0, 'Reusable reference material like the chart of accounts is exactly what project knowledge supports.',
 'beginner', 'mcq', 'Think about what''s re-used every single month during close.', 25),
((select id from public.modules where slug='projects'), 'finance',
 'Everyone''s chats inside a shared Project draw on the same custom instructions and knowledge files, which helps keep outputs _____ across a team.',
 '["consistent", "random", "private", "slower"]'::jsonb,
 0, 'Shared standing instructions and knowledge keep multiple people''s outputs aligned rather than drifting apart.',
 'intermediate', 'fill_blank', 'Think about what a shared standard does for a team''s output.', 26),
((select id from public.modules where slug='projects'), 'finance',
 'A Forecasting Project''s knowledge base has grown to include several superseded versions of the assumptions file. What should the team do?',
 '["Prune the outdated versions so Claude reliably picks the current assumptions", "Add even more versions for completeness", "Leave it \u2014 Claude will always guess correctly", "Rename the Project instead of fixing the files"]'::jsonb,
 0, 'A cluttered, conflicting knowledge base makes it harder to reliably surface the correct, current assumptions.',
 'advanced', 'scenario', 'Think about what happens when multiple conflicting versions of the same file coexist.', 27);

-- ---- artifacts ----
insert into public.quiz_questions (module_id, profession, question, options, correct_index, explanation, difficulty, kind, hint, order_index) values
((select id from public.modules where slug='artifacts'), null,
 'What is a Claude Artifact?',
 '["A separate editable pane for substantial content like documents, code, or visuals", "A type of chat message that disappears after reading", "A setting for changing Claude''s response speed", "A file format only used for images"]'::jsonb,
 0, 'Artifacts render substantial, self-contained content in their own view so you can see, edit, and iterate on it.',
 'beginner', 'mcq', 'Think about what shows up in a side panel separate from the chat itself.', 1),
((select id from public.modules where slug='artifacts'), null,
 'Only code can appear as an Artifact — documents and visuals always stay in the chat.',
 '["True", "False"]'::jsonb,
 1, 'Artifacts can hold documents, code, websites, diagrams, and interactive apps — not just code.',
 'beginner', 'true_false', 'Consider the range of content types Artifacts are designed to hold.', 2),
((select id from public.modules where slug='artifacts'), null,
 'Claude builds a working interactive calculator you can click and test in a side panel. What is this?',
 '["An Artifact", "A chat export", "A saved template", "A browser plugin"]'::jsonb,
 0, 'A self-contained, interactive piece of content like this is exactly what Artifacts are designed to render.',
 'beginner', 'scenario', 'Think about where substantial, usable content shows up separate from the conversation.', 3),
((select id from public.modules where slug='artifacts'), null,
 'Asking Claude to revise something already shown in the side panel, rather than rewriting it in chat, is called _____ on an Artifact.',
 '["iterating", "exporting", "deleting", "archiving"]'::jsonb,
 0, 'Iterating means making targeted follow-up edits to the Artifact that''s already there.',
 'intermediate', 'fill_blank', 'Think of a word meaning "making repeated refinements."', 4),
((select id from public.modules where slug='artifacts'), null,
 'Why are Artifacts useful for content you plan to keep revising?',
 '["They live in a persistent, separate view instead of being buried in scrolling chat messages", "They automatically save to your hard drive", "They can never be edited once created", "They only work for images"]'::jsonb,
 0, 'A persistent, standalone view is much easier to keep referring back to and editing than hunting through a long chat.',
 'intermediate', 'mcq', 'Think about what makes something easy to find and revise later.', 5),
((select id from public.modules where slug='artifacts'), null,
 'Asking Claude to change one small detail in an Artifact, like a header color, causes it to rebuild the entire Artifact from nothing.',
 '["True", "False"]'::jsonb,
 1, 'A targeted request typically results in a targeted edit to the existing Artifact, not a full rebuild.',
 'intermediate', 'true_false', 'Consider whether a small request should require throwing away everything else.', 6),
((select id from public.modules where slug='artifacts'), null,
 'You''ve made many small tweaks to a dashboard Artifact and now want a completely different visual style. What''s the better approach?',
 '["Clearly describe the new direction and let Claude regenerate significant portions", "Keep making tiny incremental nudges toward the new style", "Start an entirely new chat with no context at all", "Ask Claude to undo every previous edit one by one"]'::jsonb,
 0, 'Small iterative edits work well for refinements, but a major style change is usually cleaner as a deliberate regeneration.',
 'advanced', 'scenario', 'Think about whether this change is a tweak or an overhaul.', 7),
((select id from public.modules where slug='artifacts'), null,
 'Deciding whether a requested change warrants a small tweak versus a full regeneration of an Artifact is a judgment call sometimes called _____ scope.',
 '["iteration", "export", "archive", "render"]'::jsonb,
 0, '"Iteration scope" describes weighing how big a change is before deciding how to request it.',
 'advanced', 'fill_blank', 'Think about what you''re scoping — the size of the edit.', 8),
((select id from public.modules where slug='artifacts'), null,
 'Why might you deliberately ask for something as an Artifact rather than just having Claude describe it in chat?',
 '["When the deliverable is meant to be reused, shared, or interacted with as a finished thing", "Because Artifacts are always shorter than chat replies", "Because chat replies cannot contain any code", "Artifacts are required for every single request"]'::jsonb,
 0, 'Artifacts are best suited to standalone, reusable, or interactive deliverables, not general conversation.',
 'advanced', 'mcq', 'Think about what kind of output benefits from living outside the flow of conversation.', 9),
((select id from public.modules where slug='artifacts'), 'recruitment',
 'What''s a good use of an Artifact for a recruiter?',
 '["A polished candidate scorecard template", "A single one-word chat reply", "A private note only Claude can see", "An email signature block"]'::jsonb,
 0, 'Substantial, reusable content like a scorecard template is a good fit for an Artifact.',
 'beginner', 'mcq', 'Think about what''s substantial and reusable enough to deserve its own editable view.', 10),
((select id from public.modules where slug='artifacts'), 'recruitment',
 'Asking Claude to "add a column for years of experience" to a candidate comparison table Artifact will update the existing table rather than create a brand-new one.',
 '["True", "False"]'::jsonb,
 0, 'Targeted requests typically result in Claude editing the existing Artifact directly.',
 'intermediate', 'true_false', 'Consider whether a specific, small request needs a whole new Artifact.', 11),
((select id from public.modules where slug='artifacts'), 'recruitment',
 'A hiring dashboard Artifact has had many small tweaks and now needs to switch from a table layout to a visual card layout entirely. What''s the better move?',
 '["Ask for a rebuild \u2014 describe the new card-based design and let Claude regenerate it", "Keep nudging the table layout toward cards one tiny change at a time", "Start over with a completely blank chat and no context", "Give up on using an Artifact for this"]'::jsonb,
 0, 'A major structural change like switching layouts entirely is better handled as a deliberate regeneration.',
 'advanced', 'scenario', 'Think about whether this is a small tweak or a fundamentally different structure.', 12),
((select id from public.modules where slug='artifacts'), 'marketing',
 'What kind of marketing content fits well as an Artifact?',
 '["A formatted content calendar or landing page mockup", "A single emoji reaction", "A one-word chat confirmation", "A private setting only visible to Claude"]'::jsonb,
 0, 'Substantial, structured marketing deliverables are exactly what Artifacts are meant to hold.',
 'beginner', 'mcq', 'Think about what''s worth its own editable view versus a quick chat reply.', 13),
((select id from public.modules where slug='artifacts'), 'marketing',
 'Asking Claude to "make the CTA button bigger" on a landing page Artifact already open in the side panel is an example of _____ on an Artifact.',
 '["iterating", "deleting", "exporting", "hiding"]'::jsonb,
 0, 'This is a targeted follow-up edit to existing content — iterating on the Artifact.',
 'intermediate', 'fill_blank', 'Think of the term for making a follow-up refinement to something already shown.', 14),
((select id from public.modules where slug='artifacts'), 'marketing',
 'A campaign one-pager Artifact has been through a dozen small edits and no longer matches the clean structure you wanted. What''s the better fix?',
 '["Describe the structure you actually want and ask Claude to regenerate it", "Keep making one more small edit indefinitely", "Abandon Artifacts and only use plain chat text from now on", "Ask a coworker to manually reformat it instead"]'::jsonb,
 0, 'Many small edits can compound into a messier result than a clean, deliberate regeneration.',
 'advanced', 'scenario', 'Think about what happens after a dozen incremental patches versus a fresh, clearly-specified rebuild.', 15),
((select id from public.modules where slug='artifacts'), 'sales',
 'What''s a natural Artifact for a sales rep to request?',
 '["A formatted proposal document or pricing comparison table", "A single-word chat reply", "A private internal note only visible to Claude", "A random unrelated image"]'::jsonb,
 0, 'Reviewable, shareable, structured content like a proposal is a strong fit for an Artifact.',
 'beginner', 'mcq', 'Think about what''s meant to be reviewed and eventually shared as a finished piece.', 16),
((select id from public.modules where slug='artifacts'), 'sales',
 'Asking Claude to "reword the executive summary, keep everything else" on a proposal Artifact will edit just that section rather than the whole document.',
 '["True", "False"]'::jsonb,
 0, 'A specific, scoped request results in a scoped edit to just that part of the Artifact.',
 'intermediate', 'true_false', 'Consider whether a narrowly-worded request needs to touch unrelated sections.', 17),
((select id from public.modules where slug='artifacts'), 'sales',
 'A proposal Artifact has been tweaked so many times its structure has become inconsistent. What''s the better approach now?',
 '["Describe the ideal structure and ask for a fresh regenerated version", "Keep patching individual inconsistencies one at a time forever", "Delete the Artifact and rebuild the whole proposal by hand", "Ignore the inconsistency and send it as-is"]'::jsonb,
 0, 'A full regeneration from a clear structure often beats continuing to patch something that''s drifted through many edits.',
 'advanced', 'scenario', 'Think about whether more small patches will fix the underlying structural drift.', 18),
((select id from public.modules where slug='artifacts'), 'engineering',
 'Why would Claude render code as an Artifact instead of just showing it in the chat?',
 '["Substantial or runnable code is typically shown separately so you can view, edit, and interact with it", "Code can never appear inside a chat message", "Artifacts are required for every code request, no matter how tiny", "It makes the code run faster"]'::jsonb,
 0, 'A separate, editable, interactive view is more useful than plain text buried in a chat for real code.',
 'beginner', 'mcq', 'Think about what makes code easier to actually use and modify.', 19),
((select id from public.modules where slug='artifacts'), 'engineering',
 'Asking Claude to "add a field for the discount percentage" to an interactive tool Artifact is an example of _____ on the Artifact.',
 '["iterating", "archiving", "exporting", "renaming"]'::jsonb,
 0, 'This is a targeted follow-up change — iterating on the existing Artifact rather than rebuilding it.',
 'intermediate', 'fill_blank', 'Think of the term for a follow-up refinement to something already generated.', 20),
((select id from public.modules where slug='artifacts'), 'engineering',
 'An Artifact-based prototype has grown tangled through many incremental feature requests. What''s the better next step?',
 '["Describe the cleaned-up structure you want and let Claude regenerate it", "Add one more small patch on top of the existing tangle", "Abandon the prototype entirely with no further action", "Ask Claude to explain the tangle without changing anything"]'::jsonb,
 0, 'Incremental patches on an already-tangled base tend to compound the mess — a deliberate rebuild is often cleaner.',
 'advanced', 'scenario', 'Think about whether one more small patch will actually untangle the structure.', 21),
((select id from public.modules where slug='artifacts'), 'hr',
 'What HR content is a good fit for an Artifact?',
 '["A formatted onboarding checklist or polished policy handout", "A single emoji confirmation", "A private setting only Claude can see", "A one-word chat reply"]'::jsonb,
 0, 'Substantial, reusable HR documents are a strong fit for Artifacts.',
 'beginner', 'mcq', 'Think about what''s worth its own editable, reusable view.', 22),
((select id from public.modules where slug='artifacts'), 'hr',
 'Asking Claude to "shorten the PTO section" on a handbook Artifact already open will typically edit just that section.',
 '["True", "False"]'::jsonb,
 0, 'A specific, targeted request results in a targeted edit to that part of the existing Artifact.',
 'intermediate', 'true_false', 'Consider whether a narrowly scoped request needs to touch the whole document.', 23),
((select id from public.modules where slug='artifacts'), 'hr',
 'An onboarding checklist Artifact has been edited piecemeal so many times that sections now overlap and repeat. What''s the better fix?',
 '["Ask Claude to regenerate the checklist from a clear, current outline", "Trim the overlaps one more time and hope it holds", "Split it into ten separate Artifacts", "Ignore the overlaps since they''re minor"]'::jsonb,
 0, 'A regeneration from a clean outline avoids carrying forward redundancy that accumulated through many small edits.',
 'advanced', 'scenario', 'Think about whether trimming again will fix the underlying redundancy or just patch around it.', 24),
((select id from public.modules where slug='artifacts'), 'finance',
 'What''s a good use of an Artifact for finance work?',
 '["A formatted budget summary or variance-analysis table", "A single-word chat confirmation", "A private setting only visible internally to Claude", "An unrelated casual comment"]'::jsonb,
 0, 'Structured, substantial financial documents are a strong fit for Artifacts.',
 'beginner', 'mcq', 'Think about what''s structured and substantial enough to deserve its own editable view.', 25),
((select id from public.modules where slug='artifacts'), 'finance',
 'Asking Claude to "update only the Q3 column with these figures" on a forecast table Artifact is an example of _____ on the Artifact.',
 '["iterating", "deleting", "hiding", "duplicating"]'::jsonb,
 0, 'This is a scoped follow-up edit — iterating on the existing table rather than rebuilding it.',
 'intermediate', 'fill_blank', 'Think of the term for a targeted follow-up change to something already shown.', 26),
((select id from public.modules where slug='artifacts'), 'finance',
 'A budget Artifact has accumulated many small structural tweaks over weeks and no longer matches your reporting standard. What''s the better approach?',
 '["Describe the standard structure you need and ask Claude to regenerate the table", "Keep making one more small fix and hope it converges", "Manually rebuild it outside of Claude entirely", "Leave it as-is since small tweaks rarely matter"]'::jsonb,
 0, 'A clean rebuild from a clear standard avoids compounding small inconsistencies accumulated from prior edits.',
 'advanced', 'scenario', 'Think about whether one more small tweak will resolve the underlying structural drift.', 27);

-- ---- tool-use ----
insert into public.quiz_questions (module_id, profession, question, options, correct_index, explanation, difficulty, kind, hint, order_index) values
((select id from public.modules where slug='tool-use'), null,
 'What does it mean for Claude to "use a tool"?',
 '["It calls on an external capability, like web search, to help answer your request", "It changes its own personality permanently", "It stops responding to further messages", "It deletes the current conversation"]'::jsonb,
 0, 'Tool use means Claude reaches beyond its own built-in knowledge to pull in outside capabilities like search or connected data.',
 'beginner', 'mcq', 'Think about what "external capability" Claude might reach for beyond what it already knows.', 1),
((select id from public.modules where slug='tool-use'), null,
 'Claude''s training data includes every event up to the current date, so web search is never necessary.',
 '["True", "False"]'::jsonb,
 1, 'Claude''s training data has a cutoff, so web search fills in current or recent information beyond that point.',
 'beginner', 'true_false', 'Consider whether Claude''s knowledge has a fixed cutoff point.', 2),
((select id from public.modules where slug='tool-use'), null,
 'You ask Claude about a news event from this morning. What capability helps it answer accurately?',
 '["Web search", "Its training data alone", "A calculator", "A spellchecker"]'::jsonb,
 0, 'Very recent events fall outside Claude''s training data, so a live web search is what supplies current information.',
 'beginner', 'scenario', 'Think about what''s needed for information that''s too recent to be in training data.', 3),
((select id from public.modules where slug='tool-use'), null,
 'A pre-built integration that lets Claude read from or act on a specific external app, like a calendar, is called a _____.',
 '["connector", "cache", "cutoff", "checkpoint"]'::jsonb,
 0, 'A connector links Claude to a specific external app so it can read or act on real data there.',
 'intermediate', 'fill_blank', 'Think of a word describing something that links two systems together.', 4),
((select id from public.modules where slug='tool-use'), null,
 'Why might Claude search the web instead of answering purely from what it already knows?',
 '["When a question depends on current or time-sensitive information beyond its training cutoff", "Because it always prefers search over its own knowledge", "Because search is required for every single question", "Because its own knowledge is never reliable"]'::jsonb,
 0, 'Search is most useful specifically for current, time-sensitive, or very recent information that training data can''t cover.',
 'intermediate', 'mcq', 'Think about what kind of question training data alone can''t answer.', 5),
((select id from public.modules where slug='tool-use'), null,
 'MCP (Model Context Protocol) is an open standard for connecting Claude to external tools and data sources.',
 '["True", "False"]'::jsonb,
 0, 'MCP is exactly that — a standardized way for Claude to connect to outside tools and data consistently.',
 'intermediate', 'true_false', 'Consider what the acronym is describing — a protocol for what kind of connection.', 6),
((select id from public.modules where slug='tool-use'), null,
 'Claude searches the web and summarizes a statistic you plan to use in an important decision. What''s the safest next step?',
 '["Check the original source before relying on the summarized number", "Use it immediately without checking, since search results are always accurate", "Ignore the search result entirely", "Ask Claude to search again for the exact same thing"]'::jsonb,
 0, 'Summaries can be imprecise or based on an outdated source, so decision-critical numbers deserve direct verification.',
 'advanced', 'scenario', 'Think about what could go wrong between the original source and a quick summary of it.', 7),
((select id from public.modules where slug='tool-use'), null,
 'Staying aware of what a connector or tool is actually doing on your behalf — rather than trusting it blindly — is sometimes called tool-use _____.',
 '["oversight", "automation", "latency", "encryption"]'::jsonb,
 0, 'Tool-use oversight means keeping an eye on the real actions tools take, since they can affect real systems, not just chat replies.',
 'advanced', 'fill_blank', 'Think of a word meaning "keeping watch" over what''s happening.', 8),
((select id from public.modules where slug='tool-use'), null,
 'Why does connector access deserve more caution than a plain chat answer?',
 '["A connector can read or write real data in an external system, so mistakes have real consequences", "Connectors always require a paid subscription", "Connectors are slower than typing manually", "Connectors can only be used once per day"]'::jsonb,
 0, 'Because a connector interacts with a live external system, an error acted on through it can affect real data, not just produce a wrong chat message.',
 'advanced', 'mcq', 'Think about what''s different between a wrong answer in chat and a wrong action taken in a real system.', 9),
((select id from public.modules where slug='tool-use'), 'recruitment',
 'How might web search help a recruiter using Claude?',
 '["Looking up current salary benchmarks or recent company news", "Automatically hiring a candidate", "Deleting old job postings", "Changing Claude''s writing tone permanently"]'::jsonb,
 0, 'Web search is useful for current information like salary data or recent news that changes over time.',
 'beginner', 'mcq', 'Think about what kind of recruiting information changes frequently and needs to be current.', 10),
((select id from public.modules where slug='tool-use'), 'recruitment',
 'A candidate''s public professional presence can change frequently, making web search a good fit for checking it.',
 '["True", "False"]'::jsonb,
 0, 'Since public profiles update often, a live search is more likely to reflect current information than training data alone.',
 'intermediate', 'true_false', 'Consider how often a public profile might change compared to Claude''s training cutoff.', 11),
((select id from public.modules where slug='tool-use'), 'recruitment',
 'A calendar connector now auto-schedules interviews based on availability it reads directly. What should the recruiter do?',
 '["Closely check the first several bookings it makes", "Trust every booking immediately with no review", "Disable Claude entirely for scheduling forever", "Only use the connector for candidates, never interviewers"]'::jsonb,
 0, 'Because this connector takes real scheduling actions, an early review catches misreads before they become real conflicts.',
 'advanced', 'scenario', 'Think about what happens if the connector misreads an availability slot.', 12),
((select id from public.modules where slug='tool-use'), 'marketing',
 'Why might a marketer use web search inside a Claude chat?',
 '["To pull in current trends or competitor campaigns beyond Claude''s training cutoff", "To automatically publish a campaign", "To permanently change the brand''s logo", "To delete outdated content"]'::jsonb,
 0, 'Web search fills in current information, like recent trends, that falls outside Claude''s training data.',
 'beginner', 'mcq', 'Think about what kind of marketing information goes stale quickly.', 13),
((select id from public.modules where slug='tool-use'), 'marketing',
 'Connecting Claude to your analytics or content-management tool so it can read real campaign data directly is an example of using a _____.',
 '["connector", "cache", "font", "template"]'::jsonb,
 0, 'A connector is the integration that lets Claude read from a specific external app like an analytics tool.',
 'intermediate', 'fill_blank', 'Think of the term for a pre-built link between Claude and an external app.', 14),
((select id from public.modules where slug='tool-use'), 'marketing',
 'Claude searched the web for a competitor''s pricing and the number looks oddly specific. What should you do before using it in a strategy doc?',
 '["Check the original source directly", "Use it immediately without any verification", "Assume it must be wrong and discard it", "Ask a different AI tool instead"]'::jsonb,
 0, 'Decision-critical figures deserve direct verification since summarized search results can occasionally be imprecise.',
 'advanced', 'scenario', 'Think about what could go wrong between the original source and a summarized version of it.', 15),
((select id from public.modules where slug='tool-use'), 'sales',
 'How could web search help a sales rep prep for a call?',
 '["Pulling recent news about the prospect''s company, like funding or leadership changes", "Automatically closing the deal", "Changing the CRM''s data permanently", "Deleting old call notes"]'::jsonb,
 0, 'Recent company news is exactly the kind of current information web search is good for.',
 'beginner', 'mcq', 'Think about what kind of prospect information changes and needs to be current.', 16),
((select id from public.modules where slug='tool-use'), 'sales',
 'A connector to your CRM lets Claude read real, current deal data instead of you manually copying it in.',
 '["True", "False"]'::jsonb,
 0, 'That''s exactly what a connector is for — giving Claude direct access to live data in an external tool.',
 'intermediate', 'true_false', 'Consider what a connector is designed to let Claude do with an external system.', 17),
((select id from public.modules where slug='tool-use'), 'sales',
 'A CRM connector now updates deal stages automatically based on your conversation notes. What should you do?',
 '["Review its updates before trusting them fully", "Let it update everything with no review, since it''s automated", "Disconnect the CRM connector permanently", "Only use it for deals under a certain size"]'::jsonb,
 0, 'Since this connector writes real data into your CRM, an inaccurate mapping could quietly corrupt your actual pipeline.',
 'advanced', 'scenario', 'Think about what happens if the connector maps a note to the wrong deal stage.', 18),
((select id from public.modules where slug='tool-use'), 'engineering',
 'Why might an engineer use web search inside a Claude chat?',
 '["To look up current documentation or a framework update released after training cutoff", "To automatically deploy code to production", "To permanently delete a repository", "To compile code faster"]'::jsonb,
 0, 'Web search helps with information that''s changed or been released since Claude''s training data cutoff.',
 'beginner', 'mcq', 'Think about what kind of technical information changes frequently after a model is trained.', 19),
((select id from public.modules where slug='tool-use'), 'engineering',
 'The open standard that lets Claude connect consistently to developer tools like an issue tracker or internal API is called _____.',
 '["MCP (Model Context Protocol)", "HTTP", "JSON", "REST"]'::jsonb,
 0, 'MCP is the standard designed specifically for connecting Claude to external tools and data sources.',
 'intermediate', 'fill_blank', 'Think of the term introduced specifically for tool and data connections, not general web protocols.', 20),
((select id from public.modules where slug='tool-use'), 'engineering',
 'Claude, connected to your issue tracker via MCP, proposes closing tickets based on its read of recent commits. What should you do?',
 '["Review its proposed actions before anything gets closed", "Let it close every ticket automatically without review", "Disable the connector and never reconnect it", "Ignore the proposal entirely without reading it"]'::jsonb,
 0, 'A connector acting on a misread commit history could close a real ticket incorrectly, so reviewing proposed actions first matters.',
 'advanced', 'scenario', 'Think about what happens if the commit history is misread before a ticket gets closed.', 21),
((select id from public.modules where slug='tool-use'), 'hr',
 'How might web search help someone working in HR?',
 '["Looking up current employment law changes or benefits benchmarks", "Automatically terminating an employee", "Permanently deleting HR records", "Changing company policy without review"]'::jsonb,
 0, 'Employment law and benchmark data change over time, making them a good fit for a current web search.',
 'beginner', 'mcq', 'Think about what kind of HR information shifts and needs to stay current.', 22),
((select id from public.modules where slug='tool-use'), 'hr',
 'Connecting Claude to your HRIS via a connector lets it read real, current employee data directly instead of relying on manually exported reports.',
 '["True", "False"]'::jsonb,
 0, 'That''s the benefit of a connector — direct access to live data rather than manual copy-pasting.',
 'intermediate', 'true_false', 'Consider what a connector replaces compared to manually exporting a report.', 23),
((select id from public.modules where slug='tool-use'), 'hr',
 'An HRIS connector now lets Claude draft communications referencing specific employees'' leave balances it reads directly. What''s the key concern?',
 '["Reviewing what sensitive data is being read and shared, since privacy is at stake", "There''s no concern since the data is accurate", "The connector should read as much data as possible for completeness", "Only IT needs to worry about this, not HR"]'::jsonb,
 0, 'Because this touches sensitive personal data automatically, an overly broad or incorrect pull is a real privacy risk.',
 'advanced', 'scenario', 'Think about what kind of data is involved here and what happens if too much of it gets pulled or shared.', 24),
((select id from public.modules where slug='tool-use'), 'finance',
 'How might web search help someone doing finance work with Claude?',
 '["Looking up a current exchange rate or recent market move", "Automatically approving a transaction", "Permanently deleting financial records", "Changing the company''s accounting method"]'::jsonb,
 0, 'Live, constantly-changing data like exchange rates is exactly what web search is good for.',
 'beginner', 'mcq', 'Think about what kind of financial data changes minute to minute.', 25),
((select id from public.modules where slug='tool-use'), 'finance',
 'A connector to your accounting software lets Claude read current data directly, instead of relying on a manually pasted export.',
 '["True", "False"]'::jsonb,
 0, 'That''s the core benefit of a connector — direct, current access instead of a possibly stale manual export.',
 'intermediate', 'true_false', 'Consider what a connector replaces compared to manually exporting and pasting a report.', 26),
((select id from public.modules where slug='tool-use'), 'finance',
 'A connector now pulls live figures from your accounting system directly into a forecast draft. What should you do before trusting it?',
 '["Spot-check the pulled figures against the source", "Publish the forecast immediately with no review", "Disconnect all connectors permanently", "Assume the connector can never make a mistake"]'::jsonb,
 0, 'A connector reading the wrong period or account could silently skew numbers that look plausible at a glance, so spot-checking matters.',
 'advanced', 'scenario', 'Think about what could go wrong if the connector reads the wrong period or account without you noticing.', 27);

-- ---- workflows ----
insert into public.quiz_questions (module_id, profession, question, options, correct_index, explanation, difficulty, kind, hint, order_index) values
((select id from public.modules where slug='workflows'), null,
 'What is a "workflow" when working with Claude?',
 '["A sequence of connected steps that together accomplish a larger task", "A single one-word command", "A setting that changes Claude''s response length", "A type of file format"]'::jsonb,
 0, 'A workflow chains multiple steps together, rather than relying on one single request to do everything.',
 'beginner', 'mcq', 'Think about what "sequence of steps" implies versus a single request.', 1),
((select id from public.modules where slug='workflows'), null,
 'Breaking a big task into smaller steps makes it easier to catch and fix problems early.',
 '["True", "False"]'::jsonb,
 0, 'Smaller steps let you review and correct along the way, rather than discovering a problem buried in one huge final output.',
 'beginner', 'true_false', 'Consider what happens when you can check work partway through versus only at the very end.', 2),
((select id from public.modules where slug='workflows'), null,
 'You need Claude to research a topic, outline it, then write a full report. What''s the best approach?',
 '["Treat it as connected steps, reviewing each before moving to the next", "Ask for everything at once in a single giant request", "Skip the research step entirely to save time", "Only ask for the final report with no other steps"]'::jsonb,
 0, 'Splitting into reviewed steps catches problems early, before they carry through the whole chain.',
 'beginner', 'scenario', 'Think about what happens if an early step has an error and nobody notices until the end.', 3),
((select id from public.modules where slug='workflows'), null,
 'A workflow you''ve refined once and can reuse for the same type of task going forward is called a _____ prompt chain.',
 '["repeatable", "one-time", "hidden", "broken"]'::jsonb,
 0, 'A repeatable prompt chain is a sequence you can reuse, swapping in new details each time.',
 'intermediate', 'fill_blank', 'Think of a word meaning "can be used again."', 4),
((select id from public.modules where slug='workflows'), null,
 'Why does reviewing Claude''s output at each step of a workflow matter more than reviewing only the final result?',
 '["An early mistake can compound into every later step that builds on it", "Reviewing at each step takes less total time", "Claude cannot make mistakes in early steps", "Final results are always correct regardless of earlier steps"]'::jsonb,
 0, 'If an error goes unnoticed early on, every step that builds on it inherits that same error.',
 'intermediate', 'mcq', 'Think about what happens to a mistake made in step one by the time you reach step five.', 5),
((select id from public.modules where slug='workflows'), null,
 'Once you build a workflow for one recurring task, you have to reinvent it completely from scratch for every similar new task.',
 '["True", "False"]'::jsonb,
 1, 'A well-built workflow is meant to be reused, with new details swapped in — not rebuilt from zero each time.',
 'intermediate', 'true_false', 'Consider what "repeatable" is meant to save you from doing.', 6),
((select id from public.modules where slug='workflows'), null,
 'How should you decide where to split a multi-step workflow into separate steps?',
 '["Split at points where you''d actually want to review or could redirect the work", "Split after every single sentence, no matter how small", "Never split anything \u2014 always use one giant request", "Split randomly with no particular reasoning"]'::jsonb,
 0, 'Splitting at meaningful review or decision points adds real value — splitting everywhere just adds friction without benefit.',
 'advanced', 'scenario', 'Think about what makes a step boundary actually useful versus just extra overhead.', 7),
((select id from public.modules where slug='workflows'), null,
 'Combining several Claude capabilities in sequence — research, drafting, and formatting — into one coherent process is called an _____ workflow.',
 '["end-to-end", "isolated", "one-shot", "disconnected"]'::jsonb,
 0, '"End-to-end" describes a workflow that covers the whole task from start to finish as one connected process.',
 'advanced', 'fill_blank', 'Think of a phrase describing something that spans the whole process, start to finish.', 8),
((select id from public.modules where slug='workflows'), null,
 'A workflow built for one recurring task needs two of its five steps modified for a similar but different task. What''s the best approach?',
 '["Reuse the three steps that transfer directly and only rework the two that need to change", "Build an entirely new workflow from scratch every time", "Refuse to adapt it and use the original workflow unchanged", "Discard workflows entirely and go back to single giant prompts"]'::jsonb,
 0, 'Most of a workflow''s value usually carries over — targeted adaptation is more efficient than rebuilding from zero.',
 'advanced', 'mcq', 'Think about how much of the original workflow actually needs to change versus stays useful as-is.', 9),
((select id from public.modules where slug='workflows'), 'recruitment',
 'What might a recruitment workflow with Claude look like end-to-end?',
 '["Draft the job posting, then outreach messages, then interview questions", "One single request asking for everything with no structure", "Only ever writing a job posting and nothing else", "Randomly generated unrelated content"]'::jsonb,
 0, 'Chaining connected steps builds a complete hiring kit, rather than relying on a single giant request.',
 'beginner', 'mcq', 'Think about the natural sequence of tasks in filling a role.', 10),
((select id from public.modules where slug='workflows'), 'recruitment',
 'When screening resumes then drafting outreach then prepping interview questions, it''s best to review the shortlist before drafting outreach for it.',
 '["True", "False"]'::jsonb,
 0, 'Reviewing the shortlist first catches issues before outreach is drafted for the wrong set of candidates.',
 'intermediate', 'true_false', 'Consider what happens if the outreach step builds on an unreviewed shortlist.', 11),
((select id from public.modules where slug='workflows'), 'recruitment',
 'A resume-screening-to-outreach workflow works well, but a new role needs different screening criteria and outreach tone. What''s the best approach?',
 '["Reuse the overall structure, swapping in new criteria and tone at the relevant steps", "Build a completely new workflow from scratch", "Refuse to change anything and use the old criteria anyway", "Skip the screening step entirely for this role"]'::jsonb,
 0, 'The workflow''s shape still holds even though specific steps need real changes — full rebuilds aren''t necessary.',
 'advanced', 'scenario', 'Think about how much of the original sequence still applies versus what specifically needs updating.', 12),
((select id from public.modules where slug='workflows'), 'marketing',
 'What could a content-creation workflow with Claude include end-to-end?',
 '["Research the topic, draft an outline, write the post, then adapt it into social captions", "A single request with no distinct steps", "Only writing social captions and nothing else", "Randomly picking a topic with no research"]'::jsonb,
 0, 'This is a chain of connected steps that together build a complete content package.',
 'beginner', 'mcq', 'Think about the natural sequence from idea to finished, multi-format content.', 13),
((select id from public.modules where slug='workflows'), 'marketing',
 'Checking the outline before asking Claude to write the full post from it can save you from a full draft built on the wrong foundation.',
 '["True", "False"]'::jsonb,
 0, 'Catching an issue with the outline early avoids that issue compounding into the entire draft.',
 'intermediate', 'true_false', 'Consider what happens if the outline''s angle is wrong and it isn''t caught until after the draft is written.', 14),
((select id from public.modules where slug='workflows'), 'marketing',
 'Your blog-post workflow works well, but this campaign needs a video script instead of a blog post at the drafting step. What''s the best approach?',
 '["Keep the research and outline steps as-is, and swap only the drafting step''s output format", "Rebuild the entire workflow from scratch for video", "Skip research and outlining entirely for video content", "Refuse to adapt the workflow and use the blog-post version anyway"]'::jsonb,
 0, 'Most of the workflow''s value is in the earlier steps, which don''t need to change just because the final format does.',
 'advanced', 'scenario', 'Think about which steps actually depend on the final output format and which don''t.', 15),
((select id from public.modules where slug='workflows'), 'sales',
 'What could a deal-prep workflow with Claude look like end-to-end?',
 '["Research the prospect, draft talking points, then prepare a follow-up email", "One giant request covering the entire deal with no steps", "Only researching the prospect and nothing else", "Randomly generated unrelated content"]'::jsonb,
 0, 'This chain of connected steps builds a complete, call-ready package.',
 'beginner', 'mcq', 'Think about the natural sequence of preparing for and following up on a sales call.', 16),
((select id from public.modules where slug='workflows'), 'sales',
 'If a pitch draft and objection-handling notes both build on prospect research, it''s worth confirming the research is accurate before moving forward.',
 '["True", "False"]'::jsonb,
 0, 'An error in the research step would carry through into everything built on top of it.',
 'intermediate', 'true_false', 'Consider what happens to later steps if the earliest step contains a mistake.', 17),
((select id from public.modules where slug='workflows'), 'sales',
 'Your outreach workflow works for cold prospects, but warm referrals need a different opening in the pitch step. What''s the best approach?',
 '["Keep the research and follow-up steps unchanged, and only adjust the pitch step''s opening", "Rebuild the entire workflow from scratch for referrals", "Skip the pitch step entirely for referrals", "Refuse to adapt and use the cold-outreach pitch anyway"]'::jsonb,
 0, 'Most of the sequence transfers directly — only the piece that actually differs needs to change.',
 'advanced', 'scenario', 'Think about which step is actually different for a referral versus a cold prospect.', 18),
((select id from public.modules where slug='workflows'), 'engineering',
 'What could a code-review workflow with Claude include end-to-end?',
 '["Summarize the diff, flag potential issues, then draft review comments", "A single request to \"review this\" with no further structure", "Only flagging issues with no summary or comments", "Randomly picking lines of code to comment on"]'::jsonb,
 0, 'This chain of steps builds a complete, useful review rather than a vague single pass.',
 'beginner', 'mcq', 'Think about the natural sequence a careful human reviewer would follow.', 19),
((select id from public.modules where slug='workflows'), 'engineering',
 'Confirming Claude''s bug diagnosis is correct before asking it to draft the fix helps catch an issue before it compounds into the next step.',
 '["True", "False"]'::jsonb,
 0, 'If the diagnosis is wrong, a fix built on it will likely be wrong too — checking first avoids that compounding.',
 'intermediate', 'true_false', 'Consider what happens to the fix if the diagnosis it''s based on is incorrect.', 20),
((select id from public.modules where slug='workflows'), 'engineering',
 'Your bug-triage workflow works well for backend bugs, but frontend bugs need a different reproduction step. What''s the best approach?',
 '["Reuse the diagnose and draft-fix steps as-is, and only rework the reproduction step", "Rebuild the entire workflow from scratch for frontend bugs", "Skip the reproduction step entirely for frontend bugs", "Refuse to adapt and use the backend reproduction step anyway"]'::jsonb,
 0, 'The overall shape of the workflow still holds — only the step that genuinely differs needs to change.',
 'advanced', 'scenario', 'Think about which step actually depends on whether the bug is frontend or backend.', 21),
((select id from public.modules where slug='workflows'), 'hr',
 'What could an onboarding-content workflow with Claude look like end-to-end?',
 '["Draft the welcome email, then the checklist, then FAQ answers", "One massive request covering all onboarding content at once", "Only writing FAQ answers and nothing else", "Randomly generated unrelated content"]'::jsonb,
 0, 'This sequence of connected pieces builds a complete onboarding package.',
 'beginner', 'mcq', 'Think about the natural sequence of documents a new hire receives.', 22),
((select id from public.modules where slug='workflows'), 'hr',
 'Reviewing the welcome email''s tone before extending it across the checklist helps prevent a tone problem from repeating throughout the sequence.',
 '["True", "False"]'::jsonb,
 0, 'Catching a tone issue in the first document prevents it from being carried into every later document in the chain.',
 'intermediate', 'true_false', 'Consider what happens if the tone is off and it isn''t caught until after every document is written.', 23),
((select id from public.modules where slug='workflows'), 'hr',
 'Your onboarding workflow works well, but a new remote-hire track needs a different checklist step. What''s the best approach?',
 '["Keep the welcome email and FAQ steps as they are, and rework only the checklist step", "Rebuild the entire workflow from scratch for remote hires", "Skip the checklist step entirely for remote hires", "Refuse to adapt and use the in-office checklist anyway"]'::jsonb,
 0, 'Most of the workflow still applies — only the step that genuinely differs for remote hires needs to change.',
 'advanced', 'scenario', 'Think about which step actually depends on whether the hire is remote or in-office.', 24),
((select id from public.modules where slug='workflows'), 'finance',
 'What could a monthly reporting workflow with Claude include end-to-end?',
 '["Summarize the numbers, draft variance commentary, then format the executive summary", "One single request covering the entire report with no steps", "Only formatting the executive summary with no other steps", "Randomly generated unrelated commentary"]'::jsonb,
 0, 'This chain of connected steps builds the finished report piece by piece.',
 'beginner', 'mcq', 'Think about the natural sequence from raw numbers to a polished final report.', 25),
((select id from public.modules where slug='workflows'), 'finance',
 'Since variance commentary and the executive summary both depend on the number summary, it''s worth checking that summary for accuracy first.',
 '["True", "False"]'::jsonb,
 0, 'An early error in the number summary would carry through into everything built on top of it.',
 'intermediate', 'true_false', 'Consider what happens to later steps if the earliest step contains an inaccurate figure.', 26),
((select id from public.modules where slug='workflows'), 'finance',
 'Your close-reporting workflow works well, but the board version needs a different executive-summary step. What''s the best approach?',
 '["Keep the summarize and variance-commentary steps unchanged, and adapt only the exec-summary step", "Rebuild the entire workflow from scratch for the board version", "Skip the summarize step entirely for the board version", "Refuse to adapt and use the original exec summary anyway"]'::jsonb,
 0, 'Most of the workflow transfers directly — only the piece that genuinely needs to differ for the board audience should change.',
 'advanced', 'scenario', 'Think about which step actually depends on the specific audience receiving the report.', 27);

-- ===========================================================================
-- BADGES
-- ===========================================================================
insert into public.badges (slug, name, description, icon) values
('first-steps',    'First Steps',    'Complete your very first module and start your Claude journey.', '🌱'),
('prompt-pro',     'Prompt Pro',     'Ace the Prompting Fundamentals quiz and prove your prompting chops.', '✍️'),
('halfway-hero',   'Halfway Hero',   'Reach 50% course completion — you are officially over the hump.', '⚡'),
('perfect-score',  'Perfect Score',  'Get every question right on a module quiz.', '💯'),
('claude-master',  'Claude Master',  'Complete every module and master the full surface of Claude.', '🧠'),
('streak-starter', 'Streak Starter', 'Complete two modules and get your momentum going.', '🔥');

commit;
